# Initial spec file created by autospec ver. 0.3
# This spec file will build the rpm installation from a tarball version
# of the binaries: to create bins:
#     tar -zcvf opendx-4.1.0.tar.gz /usr/local/dx /usr/local/bin/dx
Summary: OpenDX samples
# The Summary: line should be expanded to about here -----^
Name: opendx-samples
%define version 4.1.0
Version: %{version}
Release: 1
Group: Applications/Graphics
Copyright: IBM Public License - Open Visualization Data Explorer VERSION 1.0
Source: opendx-samples-%{version}-bin.tar.gz
BuildRoot: /tmp/opendx-samples-%{version}-root
# Following are optional fields
URL: http://www.opendx.org
Distribution: OpenDX Organization
#Patch: opendx-samples-%{version}.patch
#Prefix: /usr/local/dx
BuildArchitectures: noarch
#Requires: 
#Obsoletes: 

%description
OpenDX is a uniquely powerful, full-featured software package for the visualization
of scientific, engineering and analytical data: Its open system design is built on familiar
standard interface environments. And its sophisticated data model provides users with 
great flexibility in creating visualizations.

These samples extend the package and help with understanding how to use its features.

%prep
%setup -c opendx-samples-%{version}
#%patch

%install
cp -aR . ${RPM_BUILD_ROOT-/}

%files
%dir /usr/local/dx/
%dir /usr/local/dx/samples/
%dir /usr/local/dx/samples/callmodule/
/usr/local/dx/samples/callmodule/Makefile_alphax
/usr/local/dx/samples/callmodule/Makefile_aviion
/usr/local/dx/samples/callmodule/Makefile_hp700
/usr/local/dx/samples/callmodule/Makefile_ibm6000
/usr/local/dx/samples/callmodule/Makefile_intelnt
/usr/local/dx/samples/callmodule/Makefile_sgi
/usr/local/dx/samples/callmodule/Makefile_solaris
/usr/local/dx/samples/callmodule/Makefile_sun4
%doc /usr/local/dx/samples/callmodule/Readme
/usr/local/dx/samples/callmodule/Simple.c
/usr/local/dx/samples/callmodule/ThunderStreamlines.c
/usr/local/dx/samples/callmodule/renderimage.c
/usr/local/dx/samples/callmodule/xapp_supervise.c
/usr/local/dx/samples/callmodule/callmodule_make
%dir /usr/local/dx/samples/data/
/usr/local/dx/samples/data/2D2ormorevarnotseries.data
/usr/local/dx/samples/data/2D2ormorevarnotseries.general
/usr/local/dx/samples/data/3D2ormorevarnotseries.data
/usr/local/dx/samples/data/3D2ormorevarnotseries.general
/usr/local/dx/samples/data/CO2.general
/usr/local/dx/samples/data/CO2.lis
/usr/local/dx/samples/data/CO2fragment.lis
/usr/local/dx/samples/data/FacesLoopsEdges.dx
/usr/local/dx/samples/data/FacesLoopsEdges_hole.dx
/usr/local/dx/samples/data/MOS_key.txt
/usr/local/dx/samples/data/MOS_lookup.txt
/usr/local/dx/samples/data/MOS_state_order.txt
/usr/local/dx/samples/data/MOS_states.dx
/usr/local/dx/samples/data/MOS_zips.dx
/usr/local/dx/samples/data/MRI.data
/usr/local/dx/samples/data/Polylines.dx
/usr/local/dx/samples/data/ROM_ozone.dx
%doc /usr/local/dx/samples/data/Readme
/usr/local/dx/samples/data/background.tiff
/usr/local/dx/samples/data/block_example.data
/usr/local/dx/samples/data/block_example.general
/usr/local/dx/samples/data/blue_yellow.cm
/usr/local/dx/samples/data/categorical.data
/usr/local/dx/samples/data/categorical.data1
/usr/local/dx/samples/data/census.general
/usr/local/dx/samples/data/census.spreadsheet
/usr/local/dx/samples/data/census.tab
/usr/local/dx/samples/data/census_normalized.dx
/usr/local/dx/samples/data/cloudwater.dx
/usr/local/dx/samples/data/colo_elev.general
/usr/local/dx/samples/data/colorado.tiff
/usr/local/dx/samples/data/colorado_elev.vit
/usr/local/dx/samples/data/cyan_red.cm
/usr/local/dx/samples/data/cylinder.rgb
/usr/local/dx/samples/data/cylinder.size
/usr/local/dx/samples/data/cylinder.tiff
/usr/local/dx/samples/data/datadepconnections.dx
/usr/local/dx/samples/data/datawithattribute.dx
/usr/local/dx/samples/data/deformedregular.dx
/usr/local/dx/samples/data/dx_logo.gif
/usr/local/dx/samples/data/dx_logo.tiff
/usr/local/dx/samples/data/external.data
/usr/local/dx/samples/data/externalfilter
/usr/local/dx/samples/data/externalfilter.c
/usr/local/dx/samples/data/externalfilter_alphax
/usr/local/dx/samples/data/externalfilter_hp700
/usr/local/dx/samples/data/externalfilter_ibm6000
/usr/local/dx/samples/data/externalfilter_sgi
/usr/local/dx/samples/data/externalfilter_solaris
/usr/local/dx/samples/data/fontlayout.dx
/usr/local/dx/samples/data/general.exampledata
/usr/local/dx/samples/data/general.exampleheader
/usr/local/dx/samples/data/griddeddata.data
/usr/local/dx/samples/data/grocery.txt
/usr/local/dx/samples/data/group.dx
/usr/local/dx/samples/data/head_slice.dx
/usr/local/dx/samples/data/heat.cm
/usr/local/dx/samples/data/homeown.txt
/usr/local/dx/samples/data/hyper.dx
/usr/local/dx/samples/data/image.dx
/usr/local/dx/samples/data/image.general
/usr/local/dx/samples/data/imide.rgb
/usr/local/dx/samples/data/imide.size
/usr/local/dx/samples/data/imide_potential.dx
/usr/local/dx/samples/data/invalid_field.bin
/usr/local/dx/samples/data/invalid_field.dx
/usr/local/dx/samples/data/irregirreg2.bin
/usr/local/dx/samples/data/irregirreg2.dx
/usr/local/dx/samples/data/irregular.dx
/usr/local/dx/samples/data/labelled_series.dx
/usr/local/dx/samples/data/labels.dx
/usr/local/dx/samples/data/magnetism.dx
/usr/local/dx/samples/data/majority.data
/usr/local/dx/samples/data/mixed_freq.cm
/usr/local/dx/samples/data/mri.general
/usr/local/dx/samples/data/multigrid1.dx
/usr/local/dx/samples/data/multigrid2.dx
/usr/local/dx/samples/data/multigrid3.dx
/usr/local/dx/samples/data/npp.dx
/usr/local/dx/samples/data/oriented_labels.dx
/usr/local/dx/samples/data/pos_conn.data
/usr/local/dx/samples/data/product1.dx
/usr/local/dx/samples/data/rain.cm
/usr/local/dx/samples/data/product2.dx
/usr/local/dx/samples/data/rainwater.dx
/usr/local/dx/samples/data/record_datafile
/usr/local/dx/samples/data/record_deformed
/usr/local/dx/samples/data/record_deformed.general
/usr/local/dx/samples/data/record_depconnections
/usr/local/dx/samples/data/record_depconnections.general
/usr/local/dx/samples/data/record_multiscalar
/usr/local/dx/samples/data/record_multiscalar.general
/usr/local/dx/samples/data/record_multiscalardepconn
/usr/local/dx/samples/data/record_multiscalardepconn.general
/usr/local/dx/samples/data/record_multiscalarmixed
/usr/local/dx/samples/data/record_multiscalarmixed.general
/usr/local/dx/samples/data/record_scalar
/usr/local/dx/samples/data/record_scalar.general
/usr/local/dx/samples/data/record_scalarvector1
/usr/local/dx/samples/data/record_scalarvector1.general
/usr/local/dx/samples/data/record_scalarvector2
/usr/local/dx/samples/data/record_scalarvector2.general
/usr/local/dx/samples/data/record_scattered.general
/usr/local/dx/samples/data/record_series
/usr/local/dx/samples/data/record_series.general
/usr/local/dx/samples/data/record_vectordata1
/usr/local/dx/samples/data/record_vectordata1.general
/usr/local/dx/samples/data/record_vectordata2
/usr/local/dx/samples/data/record_vectordata2.general
/usr/local/dx/samples/data/record_withheader
/usr/local/dx/samples/data/record_withheader.general
/usr/local/dx/samples/data/regseries.dx
/usr/local/dx/samples/data/regular.dx
/usr/local/dx/samples/data/regularskewed.dx
/usr/local/dx/samples/data/salesdata.data
/usr/local/dx/samples/data/salesdata.txt
/usr/local/dx/samples/data/sampletext.dx
/usr/local/dx/samples/data/solid.dx
/usr/local/dx/samples/data/segmented_black-red.cm
/usr/local/dx/samples/data/segmented_green-white.cm
/usr/local/dx/samples/data/segmented_high-freq.cm
/usr/local/dx/samples/data/segmented_hue.cm
/usr/local/dx/samples/data/segmented_low-freq.cm
/usr/local/dx/samples/data/series.dx
/usr/local/dx/samples/data/seriesdata.dx
/usr/local/dx/samples/data/southeastern_topo.dx
/usr/local/dx/samples/data/spreadsheet_2var
/usr/local/dx/samples/data/spreadsheet_2var.general
/usr/local/dx/samples/data/spreadsheet_deformed
/usr/local/dx/samples/data/spreadsheet_deformed.general
/usr/local/dx/samples/data/spreadsheet_layout.general
/usr/local/dx/samples/data/spreadsheet_scattered.general
/usr/local/dx/samples/data/spreadsheet_series.general
/usr/local/dx/samples/data/storm_data.dx
/usr/local/dx/samples/data/temp_wind.general
/usr/local/dx/samples/data/temp_wind.lis
/usr/local/dx/samples/data/temperature.dx
/usr/local/dx/samples/data/test.hdf
/usr/local/dx/samples/data/topo_one_deg.dx
/usr/local/dx/samples/data/topography_km-gray.cm
/usr/local/dx/samples/data/topography_km.cm
/usr/local/dx/samples/data/topography_m-gray.cm
/usr/local/dx/samples/data/topography_m.cm
/usr/local/dx/samples/data/velocity.dx
/usr/local/dx/samples/data/violet_to_white.cm
/usr/local/dx/samples/data/watermolecule.dx
/usr/local/dx/samples/data/wind.dx
/usr/local/dx/samples/data/windbarbs.dx
/usr/local/dx/samples/data/windbarbsdata.dx
/usr/local/dx/samples/data/zipcode.data
%dir /usr/local/dx/samples/dxlink/
/usr/local/dx/samples/dxlink/CensusData150.rgb
/usr/local/dx/samples/dxlink/CensusData150.size
/usr/local/dx/samples/dxlink/Imide_potential150.rgb
/usr/local/dx/samples/dxlink/Imide_potential150.size
/usr/local/dx/samples/dxlink/Makefile_alphax
/usr/local/dx/samples/dxlink/Makefile_aviion
/usr/local/dx/samples/dxlink/Makefile_hp700
/usr/local/dx/samples/dxlink/Makefile_ibm6000
/usr/local/dx/samples/dxlink/Makefile_intelnt
/usr/local/dx/samples/dxlink/Makefile_sgi
/usr/local/dx/samples/dxlink/Makefile_solaris
/usr/local/dx/samples/dxlink/Makefile_sun4
%doc /usr/local/dx/samples/dxlink/Readme
/usr/local/dx/samples/dxlink/Sealevel150.rgb
/usr/local/dx/samples/dxlink/Sealevel150.size
/usr/local/dx/samples/dxlink/cappediso150.rgb
/usr/local/dx/samples/dxlink/cappediso150.size
/usr/local/dx/samples/dxlink/demoapp.c
/usr/local/dx/samples/dxlink/maptoplane.c
/usr/local/dx/samples/dxlink/maptoplane.cfg
/usr/local/dx/samples/dxlink/maptoplane.net
/usr/local/dx/samples/dxlink/netlist
/usr/local/dx/samples/dxlink/sealevel.c
/usr/local/dx/samples/dxlink/sealevel.cfg
/usr/local/dx/samples/dxlink/sealevel.net
/usr/local/dx/samples/dxlink/xapp.c
/usr/local/dx/samples/dxlink/xapp_supervise.c
/usr/local/dx/samples/dxlink/dxlink_make
%dir /usr/local/dx/samples/macros/
/usr/local/dx/samples/macros/ArrangeMemberMacro.net
/usr/local/dx/samples/macros/AutoScaleMacro.net
/usr/local/dx/samples/macros/BandColorsMacro.net
/usr/local/dx/samples/macros/BarChartMacro.net
/usr/local/dx/samples/macros/CappedIsoMacro.net
/usr/local/dx/samples/macros/ClipSurfaceMacro.net
/usr/local/dx/samples/macros/ClipVolumeMacro.net
/usr/local/dx/samples/macros/ConvertColorNameListMacro.net
/usr/local/dx/samples/macros/DrapeMacro.net
/usr/local/dx/samples/macros/ExportVRML.net
/usr/local/dx/samples/macros/FactorialMacro.net
/usr/local/dx/samples/macros/FormatListMacro.net
/usr/local/dx/samples/macros/GetCategoricalLabelsMacro.net
/usr/local/dx/samples/macros/GetEventsMacro.net
/usr/local/dx/samples/macros/Image2Macro.net
/usr/local/dx/samples/macros/InsetImageMacro.net
/usr/local/dx/samples/macros/InterpolateCameraMacro.net
/usr/local/dx/samples/macros/InterpolatePositionsMacro.net
/usr/local/dx/samples/macros/KeyFrameCameraMacro.net
/usr/local/dx/samples/macros/MOS_statesMacro.net
/usr/local/dx/samples/macros/Make3DFieldMacro.net
/usr/local/dx/samples/macros/MakeLineMacro.net
/usr/local/dx/samples/macros/MapOnStatesMacro.net
/usr/local/dx/samples/macros/MatteMacro.net
/usr/local/dx/samples/macros/PickPlotMacro.net
/usr/local/dx/samples/macros/UnsquishGlyphMacro.net
/usr/local/dx/samples/macros/WindBarbsMacro.net
%dir /usr/local/dx/samples/outboard/
/usr/local/dx/samples/outboard/Makefile_alphax
/usr/local/dx/samples/outboard/Makefile_aviion
/usr/local/dx/samples/outboard/Makefile_hp700
/usr/local/dx/samples/outboard/Makefile_ibm6000
/usr/local/dx/samples/outboard/Makefile_ibmpvs
/usr/local/dx/samples/outboard/Makefile_intelnt
/usr/local/dx/samples/outboard/Makefile_os2
/usr/local/dx/samples/outboard/Makefile_sgi
/usr/local/dx/samples/outboard/Makefile_solaris
/usr/local/dx/samples/outboard/Makefile_sun4
%doc /usr/local/dx/samples/outboard/Readme
/usr/local/dx/samples/outboard/async.c
/usr/local/dx/samples/outboard/async.mdf
/usr/local/dx/samples/outboard/dummy.c
/usr/local/dx/samples/outboard/hello.c
/usr/local/dx/samples/outboard/hello.mdf
/usr/local/dx/samples/outboard/makedata
/usr/local/dx/samples/outboard/my_simulation.c
/usr/local/dx/samples/outboard/socket.c
/usr/local/dx/samples/outboard/watchfile.c
/usr/local/dx/samples/outboard/watchfile.mdf
/usr/local/dx/samples/outboard/watchsocket.c
/usr/local/dx/samples/outboard/watchsocket.cfg
/usr/local/dx/samples/outboard/watchsocket.mdf
/usr/local/dx/samples/outboard/watchsocket.net
%dir /usr/local/dx/samples/program_guide/
/usr/local/dx/samples/program_guide/Makefile_alphax
/usr/local/dx/samples/program_guide/Makefile_aviion
/usr/local/dx/samples/program_guide/Makefile_hp700
/usr/local/dx/samples/program_guide/Makefile_ibm6000
/usr/local/dx/samples/program_guide/Makefile_ibmpvs
/usr/local/dx/samples/program_guide/Makefile_intelnt
/usr/local/dx/samples/program_guide/Makefile_os2
/usr/local/dx/samples/program_guide/Makefile_sgi
/usr/local/dx/samples/program_guide/Makefile_solaris
/usr/local/dx/samples/program_guide/Makefile_sun4
%doc /usr/local/dx/samples/program_guide/Readme
/usr/local/dx/samples/program_guide/add.c
/usr/local/dx/samples/program_guide/add.cfg
/usr/local/dx/samples/program_guide/add.mb
/usr/local/dx/samples/program_guide/add.mdf
/usr/local/dx/samples/program_guide/add.net
/usr/local/dx/samples/program_guide/add2.c
/usr/local/dx/samples/program_guide/add2.cfg
/usr/local/dx/samples/program_guide/add2.mb
/usr/local/dx/samples/program_guide/add2.mdf
/usr/local/dx/samples/program_guide/add2.net
/usr/local/dx/samples/program_guide/add2_invalid.cfg
/usr/local/dx/samples/program_guide/add2_invalid.net
/usr/local/dx/samples/program_guide/add2invalid.c
/usr/local/dx/samples/program_guide/add2invalid.mb
/usr/local/dx/samples/program_guide/add2invalid.mdf
/usr/local/dx/samples/program_guide/add_parallel.c
/usr/local/dx/samples/program_guide/add_parallel.cfg
/usr/local/dx/samples/program_guide/add_parallel.net
/usr/local/dx/samples/program_guide/addpar.mdf
/usr/local/dx/samples/program_guide/all.mdf
/usr/local/dx/samples/program_guide/averagecell.c
/usr/local/dx/samples/program_guide/averagecell.cfg
/usr/local/dx/samples/program_guide/averagecell.mb
/usr/local/dx/samples/program_guide/averagecell.mdf
/usr/local/dx/samples/program_guide/averagecell.net
/usr/local/dx/samples/program_guide/averagecell2.mdf
/usr/local/dx/samples/program_guide/averagecell_parallel.c
/usr/local/dx/samples/program_guide/averagecell_parallel.cfg
/usr/local/dx/samples/program_guide/averagecell_parallel.net
/usr/local/dx/samples/program_guide/averagecellpar.mdf
/usr/local/dx/samples/program_guide/hello.c
/usr/local/dx/samples/program_guide/hello.cfg
/usr/local/dx/samples/program_guide/hello.mdf
/usr/local/dx/samples/program_guide/hello.net
/usr/local/dx/samples/program_guide/helloerr.mdf
/usr/local/dx/samples/program_guide/hello_errorchecking.c
/usr/local/dx/samples/program_guide/hello_errorchecking.cfg
/usr/local/dx/samples/program_guide/hello_errorchecking.net
/usr/local/dx/samples/program_guide/hello_loadable.mdf
/usr/local/dx/samples/program_guide/hello_outboard.mdf
/usr/local/dx/samples/program_guide/makex.c
/usr/local/dx/samples/program_guide/makex.cfg
/usr/local/dx/samples/program_guide/makex.mb
/usr/local/dx/samples/program_guide/makex.mdf
/usr/local/dx/samples/program_guide/makex.net
/usr/local/dx/samples/program_guide/makex_efficient.cfg
/usr/local/dx/samples/program_guide/makex_efficient.net
/usr/local/dx/samples/program_guide/makexeff.c
/usr/local/dx/samples/program_guide/makexeff.mb
/usr/local/dx/samples/program_guide/makexeff.mdf
/usr/local/dx/samples/program_guide/showpick.c
/usr/local/dx/samples/program_guide/showpick.cfg
/usr/local/dx/samples/program_guide/showpick.mdf
/usr/local/dx/samples/program_guide/showpick.net
/usr/local/dx/samples/program_guide/simpleimport.c
/usr/local/dx/samples/program_guide/simpleimport.mdf
/usr/local/dx/samples/program_guide/simpleimportfilter.c
%dir /usr/local/dx/samples/programs/
/usr/local/dx/samples/programs/Accumulate.cfg
/usr/local/dx/samples/programs/Accumulate.net
/usr/local/dx/samples/programs/AlternateVisualizations.cfg
/usr/local/dx/samples/programs/AlternateVisualizations.net
/usr/local/dx/samples/programs/AnnotationGlyphs.cfg
/usr/local/dx/samples/programs/AnnotationGlyphs.net
/usr/local/dx/samples/programs/Arrange.cfg
/usr/local/dx/samples/programs/Arrange.net
/usr/local/dx/samples/programs/AutoAxes.cfg
/usr/local/dx/samples/programs/AutoAxes.net
/usr/local/dx/samples/programs/AutoAxesSpecifyTicks.cfg
/usr/local/dx/samples/programs/AutoAxesSpecifyTicks.net
/usr/local/dx/samples/programs/AutoColor.cfg
/usr/local/dx/samples/programs/AutoColor.net
/usr/local/dx/samples/programs/AutoGlyph.cfg
/usr/local/dx/samples/programs/AutoGlyph.net
/usr/local/dx/samples/programs/AutoGrid.cfg
/usr/local/dx/samples/programs/AutoGrid.net
/usr/local/dx/samples/programs/Band.cfg
/usr/local/dx/samples/programs/Band.net
/usr/local/dx/samples/programs/BandedColors.cfg
/usr/local/dx/samples/programs/BandedColors.net
/usr/local/dx/samples/programs/Bounce.cfg
/usr/local/dx/samples/programs/Bounce.net
/usr/local/dx/samples/programs/CappedIso.cfg
/usr/local/dx/samples/programs/CappedIso.net
/usr/local/dx/samples/programs/Caption.cfg
/usr/local/dx/samples/programs/Caption.net
/usr/local/dx/samples/programs/Categorical.cfg
/usr/local/dx/samples/programs/Categorical.net
/usr/local/dx/samples/programs/CensusData.cfg
/usr/local/dx/samples/programs/CensusData.net
/usr/local/dx/samples/programs/Color.cfg
/usr/local/dx/samples/programs/Color.net
/usr/local/dx/samples/programs/ColorBar.cfg
/usr/local/dx/samples/programs/ColorBar.net
/usr/local/dx/samples/programs/Compute2.cfg
/usr/local/dx/samples/programs/Compute2.net
/usr/local/dx/samples/programs/ComputeMultiLine.cfg
/usr/local/dx/samples/programs/ComputeMultiLine.net
/usr/local/dx/samples/programs/ComputeOnData.cfg
/usr/local/dx/samples/programs/ComputeOnData.net
/usr/local/dx/samples/programs/Connect.cfg
/usr/local/dx/samples/programs/Connect.net
/usr/local/dx/samples/programs/ConnectingScatteredPoints.cfg
/usr/local/dx/samples/programs/ConnectingScatteredPoints.net
/usr/local/dx/samples/programs/Construct.cfg
/usr/local/dx/samples/programs/Construct.net
/usr/local/dx/samples/programs/ContoursAndCaption.cfg
/usr/local/dx/samples/programs/ContoursAndCaption.net
/usr/local/dx/samples/programs/DataDrivenInteractors.cfg
/usr/local/dx/samples/programs/DataDrivenInteractors.net
/usr/local/dx/samples/programs/DataDrivenSelector.cfg
/usr/local/dx/samples/programs/DataDrivenSelector.net
/usr/local/dx/samples/programs/Describe.cfg
/usr/local/dx/samples/programs/Describe.net
/usr/local/dx/samples/programs/DialogStyle.cfg
/usr/local/dx/samples/programs/DialogStyle.net
/usr/local/dx/samples/programs/Distributed.cfg
/usr/local/dx/samples/programs/Distributed.net
/usr/local/dx/samples/programs/Duplicates.cfg
/usr/local/dx/samples/programs/Duplicates.net
/usr/local/dx/samples/programs/ExamplePieChart.cfg
/usr/local/dx/samples/programs/ExamplePieChart.net
/usr/local/dx/samples/programs/ExampleSMP.cfg
/usr/local/dx/samples/programs/ExampleSMP.net
/usr/local/dx/samples/programs/ExpandedFonts.cfg
/usr/local/dx/samples/programs/ExpandedFonts.net
/usr/local/dx/samples/programs/FFT.cfg
/usr/local/dx/samples/programs/FFT.net
/usr/local/dx/samples/programs/FaceNormals.cfg
/usr/local/dx/samples/programs/FaceNormals.net
/usr/local/dx/samples/programs/Factorial.cfg
/usr/local/dx/samples/programs/Factorial.net
/usr/local/dx/samples/programs/FatLines.cfg
/usr/local/dx/samples/programs/FatLines.net
/usr/local/dx/samples/programs/FlyThrough.cfg
/usr/local/dx/samples/programs/FlyThrough.net
/usr/local/dx/samples/programs/FlyThrough2.cfg
/usr/local/dx/samples/programs/FlyThrough2.net
/usr/local/dx/samples/programs/FontLayouts.cfg
/usr/local/dx/samples/programs/FontLayouts.net
/usr/local/dx/samples/programs/FontPreview.cfg
/usr/local/dx/samples/programs/FontPreview.net
/usr/local/dx/samples/programs/GeneralImport1.cfg
/usr/local/dx/samples/programs/GeneralImport1.net
/usr/local/dx/samples/programs/GeneralImport2.cfg
/usr/local/dx/samples/programs/GeneralImport2.net
/usr/local/dx/samples/programs/GetSet.cfg
/usr/local/dx/samples/programs/GetSet.net
/usr/local/dx/samples/programs/Gradient.cfg
/usr/local/dx/samples/programs/Gradient.net
/usr/local/dx/samples/programs/Grid.cfg
/usr/local/dx/samples/programs/Grid.net
/usr/local/dx/samples/programs/GroceryList.cfg
/usr/local/dx/samples/programs/GroceryList.net
/usr/local/dx/samples/programs/Histogram.cfg
/usr/local/dx/samples/programs/Histogram.net
/usr/local/dx/samples/programs/HomeOwn.cfg
/usr/local/dx/samples/programs/HomeOwn.net
/usr/local/dx/samples/programs/ImageTool.cfg
/usr/local/dx/samples/programs/ImageTool.net
/usr/local/dx/samples/programs/Image_wo_UI.cfg
/usr/local/dx/samples/programs/Image_wo_UI.net
/usr/local/dx/samples/programs/Imide_potential.cfg
/usr/local/dx/samples/programs/Imide_potential.net
/usr/local/dx/samples/programs/ImportExternalFilter.cfg
/usr/local/dx/samples/programs/ImportExternalFilter.net
/usr/local/dx/samples/programs/Include.cfg
/usr/local/dx/samples/programs/Include.net
/usr/local/dx/samples/programs/IndependentlyArrange.cfg
/usr/local/dx/samples/programs/IndependentlyArrange.net
/usr/local/dx/samples/programs/InsetImage.cfg
/usr/local/dx/samples/programs/InsetImage.net
/usr/local/dx/samples/programs/InsetImageSimple.cfg
/usr/local/dx/samples/programs/InsetImageSimple.net
/usr/local/dx/samples/programs/InterfaceControl1.cfg
/usr/local/dx/samples/programs/InterfaceControl1.net
/usr/local/dx/samples/programs/InterfaceControl2.cfg
/usr/local/dx/samples/programs/InterfaceControl2.net
/usr/local/dx/samples/programs/InterfaceControl3.cfg
/usr/local/dx/samples/programs/InterfaceControl3.net
/usr/local/dx/samples/programs/Interop.cfg
/usr/local/dx/samples/programs/Interop.net
/usr/local/dx/samples/programs/InvalidData.cfg
/usr/local/dx/samples/programs/InvalidData.net
/usr/local/dx/samples/programs/Isolate.cfg
/usr/local/dx/samples/programs/Isolate.net
/usr/local/dx/samples/programs/Isosurface.cfg
/usr/local/dx/samples/programs/Isosurface.net
/usr/local/dx/samples/programs/Legend.cfg
/usr/local/dx/samples/programs/Legend.net
/usr/local/dx/samples/programs/Light.cfg
/usr/local/dx/samples/programs/Light.net
/usr/local/dx/samples/programs/MRI_1.cfg
/usr/local/dx/samples/programs/MRI_1.net
/usr/local/dx/samples/programs/MRI_2.cfg
/usr/local/dx/samples/programs/MRI_2.net
/usr/local/dx/samples/programs/Majority.cfg
/usr/local/dx/samples/programs/Majority.net
/usr/local/dx/samples/programs/ManipulateGroups.cfg
/usr/local/dx/samples/programs/ManipulateGroups.net
/usr/local/dx/samples/programs/Map.cfg
/usr/local/dx/samples/programs/Map.net
/usr/local/dx/samples/programs/MapToPlane.cfg
/usr/local/dx/samples/programs/MapToPlane.net
/usr/local/dx/samples/programs/MappedIso.cfg
/usr/local/dx/samples/programs/MappedIso.net
/usr/local/dx/samples/programs/MarkUnmark.cfg
/usr/local/dx/samples/programs/MarkUnmark.net
/usr/local/dx/samples/programs/MovingCamera.cfg
/usr/local/dx/samples/programs/MovingCamera.net
/usr/local/dx/samples/programs/MovingSheet.cfg
/usr/local/dx/samples/programs/MovingSheet.net
/usr/local/dx/samples/programs/MultipleDataSets.cfg
/usr/local/dx/samples/programs/MultipleDataSets.net
/usr/local/dx/samples/programs/PickPlot.cfg
/usr/local/dx/samples/programs/PickPlot.net
/usr/local/dx/samples/programs/PickStreamline.cfg
/usr/local/dx/samples/programs/PickStreamline.net
/usr/local/dx/samples/programs/PlotGroupOfLines.cfg
/usr/local/dx/samples/programs/PlotGroupOfLines.net
/usr/local/dx/samples/programs/PlotLine.cfg
/usr/local/dx/samples/programs/PlotLine.net
/usr/local/dx/samples/programs/PlotLine2.cfg
/usr/local/dx/samples/programs/PlotLine2.net
/usr/local/dx/samples/programs/PlotTwoLines.cfg
/usr/local/dx/samples/programs/PlotSpecifyTicks.cfg
/usr/local/dx/samples/programs/PlotSpecifyTicks.net
/usr/local/dx/samples/programs/PlotTwoLines.net
/usr/local/dx/samples/programs/Post.cfg
/usr/local/dx/samples/programs/Post.net
/usr/local/dx/samples/programs/ProbeText.cfg
/usr/local/dx/samples/programs/ProbeText.net
/usr/local/dx/samples/programs/QuantizeImage.cfg
/usr/local/dx/samples/programs/QuantizeImage.net
%doc /usr/local/dx/samples/programs/Readme
/usr/local/dx/samples/programs/Reduce.cfg
/usr/local/dx/samples/programs/Reduce.net
/usr/local/dx/samples/programs/Refine.cfg
/usr/local/dx/samples/programs/Refine.net
/usr/local/dx/samples/programs/Regrid.cfg
/usr/local/dx/samples/programs/Regrid.net
/usr/local/dx/samples/programs/Route.cfg
/usr/local/dx/samples/programs/Route.net
/usr/local/dx/samples/programs/RubberTube.cfg
/usr/local/dx/samples/programs/RubberTube.net
/usr/local/dx/samples/programs/Rubbersheet.cfg
/usr/local/dx/samples/programs/Rubbersheet.net
/usr/local/dx/samples/programs/SalesOnStates.cfg
/usr/local/dx/samples/programs/SalesOnStates.net
/usr/local/dx/samples/programs/ScaleScreen.cfg
/usr/local/dx/samples/programs/ScaleScreen.net
/usr/local/dx/samples/programs/ScalingAxes.cfg
/usr/local/dx/samples/programs/ScalingAxes.net
/usr/local/dx/samples/programs/ScatterData.cfg
/usr/local/dx/samples/programs/ScatterData.net
/usr/local/dx/samples/programs/Sealevel.cfg
/usr/local/dx/samples/programs/Sealevel.net
/usr/local/dx/samples/programs/SharedCamera.cfg
/usr/local/dx/samples/programs/SharedCamera.net
/usr/local/dx/samples/programs/ShowBoundary.cfg
/usr/local/dx/samples/programs/ShowBoundary.net
/usr/local/dx/samples/programs/ShowFonts.cfg
/usr/local/dx/samples/programs/ShowFonts.net
/usr/local/dx/samples/programs/SimpleGetSetLoop.cfg
/usr/local/dx/samples/programs/SimpleGetSetLoop.net
/usr/local/dx/samples/programs/SimplifySurface.cfg
/usr/local/dx/samples/programs/SimplifySurface.net
/usr/local/dx/samples/programs/Slab.cfg
/usr/local/dx/samples/programs/Slab.net
/usr/local/dx/samples/programs/Sort.cfg
/usr/local/dx/samples/programs/Sort.net
/usr/local/dx/samples/programs/SpecialCharacters.cfg
/usr/local/dx/samples/programs/SpecialCharacters.net
/usr/local/dx/samples/programs/StandardColormaps.cfg
/usr/local/dx/samples/programs/StandardColormaps.net
/usr/local/dx/samples/programs/Streamline.cfg
/usr/local/dx/samples/programs/Streamline.net
/usr/local/dx/samples/programs/Supervise.cfg
/usr/local/dx/samples/programs/Supervise.net
/usr/local/dx/samples/programs/SupervisePicking.cfg
/usr/local/dx/samples/programs/SupervisePicking.net
/usr/local/dx/samples/programs/Switch.cfg
/usr/local/dx/samples/programs/Switch.net
/usr/local/dx/samples/programs/TextureMapOpenGL.cfg
/usr/local/dx/samples/programs/TextureMapOpenGL.net
/usr/local/dx/samples/programs/ThunderGlyphSheet.cfg
/usr/local/dx/samples/programs/ThunderGlyphSheet.net
/usr/local/dx/samples/programs/ThunderStreamlines.cfg
/usr/local/dx/samples/programs/ThunderStreamlines.net
/usr/local/dx/samples/programs/Thunder_cellcentered.cfg
/usr/local/dx/samples/programs/Thunder_cellcentered.net
/usr/local/dx/samples/programs/Topo.cfg
/usr/local/dx/samples/programs/Topo.net
/usr/local/dx/samples/programs/UsingAttributes.cfg
/usr/local/dx/samples/programs/UsingAttributes.net
/usr/local/dx/samples/programs/UsingBarChart.cfg
/usr/local/dx/samples/programs/UsingBarChart.net
/usr/local/dx/samples/programs/UsingClipPlane.cfg
/usr/local/dx/samples/programs/UsingClipPlane.net
/usr/local/dx/samples/programs/UsingColormaps.cfg
/usr/local/dx/samples/programs/UsingColormaps.net
/usr/local/dx/samples/programs/UsingDrape.cfg
/usr/local/dx/samples/programs/UsingDrape.net
/usr/local/dx/samples/programs/UsingEqualize.cfg
/usr/local/dx/samples/programs/UsingEqualize.net
/usr/local/dx/samples/programs/UsingFilter.cfg
/usr/local/dx/samples/programs/UsingFilter.net
%dir /usr/local/dx/samples/programs/2D_DATA/
/usr/local/dx/samples/programs/2D_DATA/AlternateVisualizations.cfg
/usr/local/dx/samples/programs/2D_DATA/AlternateVisualizations.net
/usr/local/dx/samples/programs/2D_DATA/BandedColors.cfg
/usr/local/dx/samples/programs/2D_DATA/BandedColors.net
/usr/local/dx/samples/programs/2D_DATA/ConnectingScatteredPoints.cfg
/usr/local/dx/samples/programs/2D_DATA/ConnectingScatteredPoints.net
/usr/local/dx/samples/programs/2D_DATA/FFT.cfg
/usr/local/dx/samples/programs/2D_DATA/FFT.net
/usr/local/dx/samples/programs/2D_DATA/GeneralImport1.cfg
/usr/local/dx/samples/programs/2D_DATA/GeneralImport1.net
/usr/local/dx/samples/programs/2D_DATA/GeneralImport2.cfg
/usr/local/dx/samples/programs/2D_DATA/GeneralImport2.net
/usr/local/dx/samples/programs/2D_DATA/InvalidData.cfg
/usr/local/dx/samples/programs/2D_DATA/InvalidData.net
/usr/local/dx/samples/programs/2D_DATA/Sealevel.cfg
/usr/local/dx/samples/programs/2D_DATA/Sealevel.net
/usr/local/dx/samples/programs/2D_DATA/Sort.cfg
/usr/local/dx/samples/programs/2D_DATA/Sort.net
/usr/local/dx/samples/programs/2D_DATA/Topo.cfg
/usr/local/dx/samples/programs/2D_DATA/Topo.net
/usr/local/dx/samples/programs/2D_DATA/UsingDrape.cfg
/usr/local/dx/samples/programs/2D_DATA/UsingDrape.net
/usr/local/dx/samples/programs/2D_DATA/UsingFilter.cfg
/usr/local/dx/samples/programs/2D_DATA/UsingFilter.net
/usr/local/dx/samples/programs/2D_DATA/UsingIsosurface.cfg
/usr/local/dx/samples/programs/2D_DATA/UsingIsosurface.net
/usr/local/dx/samples/programs/2D_DATA/UsingMorph.cfg
/usr/local/dx/samples/programs/2D_DATA/UsingMorph.net
/usr/local/dx/samples/programs/2D_DATA/UsingOverlay.cfg
/usr/local/dx/samples/programs/2D_DATA/UsingOverlay.net
/usr/local/dx/samples/programs/UsingGlyphs.cfg
/usr/local/dx/samples/programs/UsingGlyphs.net
/usr/local/dx/samples/programs/UsingIsosurface.cfg
/usr/local/dx/samples/programs/UsingIsosurface.net
/usr/local/dx/samples/programs/UsingKeyFrameCamera.cfg
/usr/local/dx/samples/programs/UsingKeyFrameCamera.net
/usr/local/dx/samples/programs/UsingLights.cfg
/usr/local/dx/samples/programs/UsingLights.net
/usr/local/dx/samples/programs/UsingMap.cfg
/usr/local/dx/samples/programs/UsingMap.net
/usr/local/dx/samples/programs/UsingMessage.cfg
/usr/local/dx/samples/programs/UsingMessage.net
/usr/local/dx/samples/programs/UsingMorph.cfg
/usr/local/dx/samples/programs/UsingMorph.net
/usr/local/dx/samples/programs/UsingMultiGrids.cfg
/usr/local/dx/samples/programs/UsingMultiGrids.net
/usr/local/dx/samples/programs/UsingOverlay.cfg
/usr/local/dx/samples/programs/UsingOverlay.net
/usr/local/dx/samples/programs/UsingParse.cfg
/usr/local/dx/samples/programs/UsingParse.net
/usr/local/dx/samples/programs/UsingProbes.cfg
/usr/local/dx/samples/programs/UsingProbes.net
/usr/local/dx/samples/programs/UsingShade.cfg
/usr/local/dx/samples/programs/UsingShade.net
/usr/local/dx/samples/programs/UsingStreakline.cfg
/usr/local/dx/samples/programs/UsingStreakline.net
/usr/local/dx/samples/programs/UsingSwitchAndRoute.cfg
/usr/local/dx/samples/programs/UsingSwitchAndRoute.net
/usr/local/dx/samples/programs/UsingTextAndTextGlyphs.cfg
/usr/local/dx/samples/programs/UsingTextAndTextGlyphs.net
/usr/local/dx/samples/programs/Verify.cfg
/usr/local/dx/samples/programs/Verify.net
/usr/local/dx/samples/programs/VisualObject.cfg
/usr/local/dx/samples/programs/VisualObject.net
/usr/local/dx/samples/programs/VolumeClip.cfg
/usr/local/dx/samples/programs/VolumeClip.net
/usr/local/dx/samples/programs/VolumeRendering.cfg
/usr/local/dx/samples/programs/VolumeRendering.net
/usr/local/dx/samples/programs/VolumeRenderingSimple.cfg
/usr/local/dx/samples/programs/VolumeRenderingSimple.net
/usr/local/dx/samples/programs/WarpingPositions.cfg
/usr/local/dx/samples/programs/WarpingPositions.net
/usr/local/dx/samples/programs/WindBarbs.cfg
/usr/local/dx/samples/programs/WindBarbs.net
/usr/local/dx/samples/programs/WindVorticity.cfg
/usr/local/dx/samples/programs/WindVorticity.net
/usr/local/dx/samples/programs/ZipCodes.cfg
/usr/local/dx/samples/programs/ZipCodes.net
%dir /usr/local/dx/samples/programs/3D_DATA/
/usr/local/dx/samples/programs/3D_DATA/AnnotationGlyphs.cfg
/usr/local/dx/samples/programs/3D_DATA/AnnotationGlyphs.net
/usr/local/dx/samples/programs/3D_DATA/AutoColor.cfg
/usr/local/dx/samples/programs/3D_DATA/AutoColor.net
/usr/local/dx/samples/programs/3D_DATA/CappedIso.cfg
/usr/local/dx/samples/programs/3D_DATA/CappedIso.net
/usr/local/dx/samples/programs/3D_DATA/ComputeOnData.cfg
/usr/local/dx/samples/programs/3D_DATA/ComputeOnData.net
/usr/local/dx/samples/programs/3D_DATA/ContoursAndCaption.cfg
/usr/local/dx/samples/programs/3D_DATA/ContoursAndCaption.net
/usr/local/dx/samples/programs/3D_DATA/Distributed.cfg
/usr/local/dx/samples/programs/3D_DATA/Distributed.net
/usr/local/dx/samples/programs/3D_DATA/FlyThrough.cfg
/usr/local/dx/samples/programs/3D_DATA/FlyThrough.net
/usr/local/dx/samples/programs/3D_DATA/FlyThrough2.cfg
/usr/local/dx/samples/programs/3D_DATA/FlyThrough2.net
/usr/local/dx/samples/programs/3D_DATA/Imide_potential.cfg
/usr/local/dx/samples/programs/3D_DATA/Imide_potential.net
/usr/local/dx/samples/programs/3D_DATA/Isolate.cfg
/usr/local/dx/samples/programs/3D_DATA/Isolate.net
/usr/local/dx/samples/programs/3D_DATA/MRI_2.cfg
/usr/local/dx/samples/programs/3D_DATA/MRI_2.net
/usr/local/dx/samples/programs/3D_DATA/MappedIso.cfg
/usr/local/dx/samples/programs/3D_DATA/MappedIso.net
/usr/local/dx/samples/programs/3D_DATA/MovingCamera.cfg
/usr/local/dx/samples/programs/3D_DATA/MovingCamera.net
/usr/local/dx/samples/programs/3D_DATA/MovingSheet.cfg
/usr/local/dx/samples/programs/3D_DATA/MovingSheet.net
/usr/local/dx/samples/programs/3D_DATA/PickStreamline.cfg
/usr/local/dx/samples/programs/3D_DATA/PickStreamline.net
/usr/local/dx/samples/programs/3D_DATA/PlotLine.cfg
/usr/local/dx/samples/programs/3D_DATA/PlotLine.net
/usr/local/dx/samples/programs/3D_DATA/PlotLine2.cfg
/usr/local/dx/samples/programs/3D_DATA/PlotLine2.net
/usr/local/dx/samples/programs/3D_DATA/PlotTwoLines.cfg
/usr/local/dx/samples/programs/3D_DATA/PlotTwoLines.net
/usr/local/dx/samples/programs/3D_DATA/ProbeText.cfg
/usr/local/dx/samples/programs/3D_DATA/ProbeText.net
/usr/local/dx/samples/programs/3D_DATA/RubberTube.cfg
/usr/local/dx/samples/programs/3D_DATA/RubberTube.net
/usr/local/dx/samples/programs/3D_DATA/SharedCamera.cfg
/usr/local/dx/samples/programs/3D_DATA/SharedCamera.net
/usr/local/dx/samples/programs/3D_DATA/SimplifySurface.cfg
/usr/local/dx/samples/programs/3D_DATA/SimplifySurface.net
/usr/local/dx/samples/programs/3D_DATA/Streamline.cfg
/usr/local/dx/samples/programs/3D_DATA/Streamline.net
/usr/local/dx/samples/programs/3D_DATA/ThunderGlyphSheet.cfg
/usr/local/dx/samples/programs/3D_DATA/ThunderGlyphSheet.net
/usr/local/dx/samples/programs/3D_DATA/ThunderStreamlines.cfg
/usr/local/dx/samples/programs/3D_DATA/ThunderStreamlines.net
/usr/local/dx/samples/programs/3D_DATA/Thunder_cellcentered.cfg
/usr/local/dx/samples/programs/3D_DATA/Thunder_cellcentered.net
/usr/local/dx/samples/programs/3D_DATA/UsingClipPlane.cfg
/usr/local/dx/samples/programs/3D_DATA/UsingClipPlane.net
/usr/local/dx/samples/programs/3D_DATA/UsingGlyphs.cfg
/usr/local/dx/samples/programs/3D_DATA/UsingGlyphs.net
/usr/local/dx/samples/programs/3D_DATA/UsingIsosurface.cfg
/usr/local/dx/samples/programs/3D_DATA/UsingIsosurface.net
/usr/local/dx/samples/programs/3D_DATA/UsingMap.cfg
/usr/local/dx/samples/programs/3D_DATA/UsingMap.net
/usr/local/dx/samples/programs/3D_DATA/UsingStreakline.cfg
/usr/local/dx/samples/programs/3D_DATA/UsingStreakline.net
/usr/local/dx/samples/programs/3D_DATA/VolumeClip.cfg
/usr/local/dx/samples/programs/3D_DATA/VolumeClip.net
/usr/local/dx/samples/programs/3D_DATA/VolumeRendering.cfg
/usr/local/dx/samples/programs/3D_DATA/VolumeRendering.net
/usr/local/dx/samples/programs/3D_DATA/VolumeRenderingSimple.cfg
/usr/local/dx/samples/programs/3D_DATA/VolumeRenderingSimple.net
/usr/local/dx/samples/programs/3D_DATA/WindVorticity.cfg
/usr/local/dx/samples/programs/3D_DATA/WindVorticity.net
%dir /usr/local/dx/samples/programs/ANNOTATION/
/usr/local/dx/samples/programs/ANNOTATION/AnnotationGlyphs.cfg
/usr/local/dx/samples/programs/ANNOTATION/AnnotationGlyphs.net
/usr/local/dx/samples/programs/ANNOTATION/AutoAxesSpecifyTicks.cfg
/usr/local/dx/samples/programs/ANNOTATION/AutoAxesSpecifyTicks.net
/usr/local/dx/samples/programs/ANNOTATION/BandedColors.cfg
/usr/local/dx/samples/programs/ANNOTATION/BandedColors.net
/usr/local/dx/samples/programs/ANNOTATION/Categorical.cfg
/usr/local/dx/samples/programs/ANNOTATION/Categorical.net
/usr/local/dx/samples/programs/ANNOTATION/ContoursAndCaption.cfg
/usr/local/dx/samples/programs/ANNOTATION/ContoursAndCaption.net
/usr/local/dx/samples/programs/ANNOTATION/Distributed.cfg
/usr/local/dx/samples/programs/ANNOTATION/Distributed.net
/usr/local/dx/samples/programs/ANNOTATION/ExpandedFonts.cfg
/usr/local/dx/samples/programs/ANNOTATION/ExpandedFonts.net
/usr/local/dx/samples/programs/ANNOTATION/FontLayouts.cfg
/usr/local/dx/samples/programs/ANNOTATION/FontLayouts.net
/usr/local/dx/samples/programs/ANNOTATION/FontPreview.cfg
/usr/local/dx/samples/programs/ANNOTATION/FontPreview.net
/usr/local/dx/samples/programs/ANNOTATION/GroceryList.cfg
/usr/local/dx/samples/programs/ANNOTATION/GroceryList.net
/usr/local/dx/samples/programs/ANNOTATION/Imide_potential.cfg
/usr/local/dx/samples/programs/ANNOTATION/Imide_potential.net
/usr/local/dx/samples/programs/ANNOTATION/Legend.cfg
/usr/local/dx/samples/programs/ANNOTATION/Legend.net
/usr/local/dx/samples/programs/ANNOTATION/PickPlot.cfg
/usr/local/dx/samples/programs/ANNOTATION/PickPlot.net
/usr/local/dx/samples/programs/ANNOTATION/PlotGroupOfLines.cfg
/usr/local/dx/samples/programs/ANNOTATION/PlotGroupOfLines.net
/usr/local/dx/samples/programs/ANNOTATION/PlotLine.cfg
/usr/local/dx/samples/programs/ANNOTATION/PlotLine.net
/usr/local/dx/samples/programs/ANNOTATION/PlotLine2.cfg
/usr/local/dx/samples/programs/ANNOTATION/PlotLine2.net
/usr/local/dx/samples/programs/ANNOTATION/PlotSpecifyTicks.cfg
/usr/local/dx/samples/programs/ANNOTATION/PlotSpecifyTicks.net
/usr/local/dx/samples/programs/ANNOTATION/PlotTwoLines.cfg
/usr/local/dx/samples/programs/ANNOTATION/PlotTwoLines.net
/usr/local/dx/samples/programs/ANNOTATION/ProbeText.cfg
/usr/local/dx/samples/programs/ANNOTATION/ProbeText.net
/usr/local/dx/samples/programs/ANNOTATION/SalesOnStates.cfg
/usr/local/dx/samples/programs/ANNOTATION/SalesOnStates.net
/usr/local/dx/samples/programs/ANNOTATION/ScalingAxes.cfg
/usr/local/dx/samples/programs/ANNOTATION/ScalingAxes.net
/usr/local/dx/samples/programs/ANNOTATION/ShowFonts.cfg
/usr/local/dx/samples/programs/ANNOTATION/ShowFonts.net
/usr/local/dx/samples/programs/ANNOTATION/Sort.cfg
/usr/local/dx/samples/programs/ANNOTATION/Sort.net
/usr/local/dx/samples/programs/ANNOTATION/SpecialCharacters.cfg
/usr/local/dx/samples/programs/ANNOTATION/SpecialCharacters.net
/usr/local/dx/samples/programs/ANNOTATION/ThunderGlyphSheet.cfg
/usr/local/dx/samples/programs/ANNOTATION/ThunderGlyphSheet.net
/usr/local/dx/samples/programs/ANNOTATION/UsingGlyphs.cfg
/usr/local/dx/samples/programs/ANNOTATION/UsingGlyphs.net
/usr/local/dx/samples/programs/ANNOTATION/UsingTextAndTextGlyphs.cfg
/usr/local/dx/samples/programs/ANNOTATION/UsingTextAndTextGlyphs.net
%dir /usr/local/dx/samples/programs/CATEGORICAL/
/usr/local/dx/samples/programs/CATEGORICAL/Categorical.cfg
/usr/local/dx/samples/programs/CATEGORICAL/Categorical.net
/usr/local/dx/samples/programs/CATEGORICAL/Duplicates.cfg
/usr/local/dx/samples/programs/CATEGORICAL/Duplicates.net
/usr/local/dx/samples/programs/CATEGORICAL/ExamplePieChart.cfg
/usr/local/dx/samples/programs/CATEGORICAL/ExamplePieChart.net
/usr/local/dx/samples/programs/CATEGORICAL/GroceryList.cfg
/usr/local/dx/samples/programs/CATEGORICAL/GroceryList.net
/usr/local/dx/samples/programs/CATEGORICAL/Legend.cfg
/usr/local/dx/samples/programs/CATEGORICAL/Legend.net
/usr/local/dx/samples/programs/CATEGORICAL/SalesOnStates.cfg
/usr/local/dx/samples/programs/CATEGORICAL/SalesOnStates.net
/usr/local/dx/samples/programs/CATEGORICAL/ZipCodes.cfg
/usr/local/dx/samples/programs/CATEGORICAL/ZipCodes.net
%dir /usr/local/dx/samples/programs/COLORMAP_EDITOR/
/usr/local/dx/samples/programs/COLORMAP_EDITOR/DataDrivenInteractors.cfg
/usr/local/dx/samples/programs/COLORMAP_EDITOR/DataDrivenInteractors.net
/usr/local/dx/samples/programs/COLORMAP_EDITOR/Imide_potential.cfg
/usr/local/dx/samples/programs/COLORMAP_EDITOR/Imide_potential.net
/usr/local/dx/samples/programs/COLORMAP_EDITOR/StandardColormaps.cfg
/usr/local/dx/samples/programs/COLORMAP_EDITOR/StandardColormaps.net
/usr/local/dx/samples/programs/COLORMAP_EDITOR/UsingColormaps.cfg
/usr/local/dx/samples/programs/COLORMAP_EDITOR/UsingColormaps.net
/usr/local/dx/samples/programs/COLORMAP_EDITOR/VolumeRendering.cfg
/usr/local/dx/samples/programs/COLORMAP_EDITOR/VolumeRendering.net
%dir /usr/local/dx/samples/programs/COMPUTE/
/usr/local/dx/samples/programs/COMPUTE/Bounce.cfg
/usr/local/dx/samples/programs/COMPUTE/Bounce.net
/usr/local/dx/samples/programs/COMPUTE/Compute2.cfg
/usr/local/dx/samples/programs/COMPUTE/Compute2.net
/usr/local/dx/samples/programs/COMPUTE/ComputeMultiLine.cfg
/usr/local/dx/samples/programs/COMPUTE/ComputeMultiLine.net
/usr/local/dx/samples/programs/COMPUTE/ComputeOnData.cfg
/usr/local/dx/samples/programs/COMPUTE/ComputeOnData.net
/usr/local/dx/samples/programs/COMPUTE/WarpingPositions.cfg
/usr/local/dx/samples/programs/COMPUTE/WarpingPositions.net
%dir /usr/local/dx/samples/programs/DATA_DRIVEN_INTERACTORS/
/usr/local/dx/samples/programs/DATA_DRIVEN_INTERACTORS/DataDrivenInteractors.cfg
/usr/local/dx/samples/programs/DATA_DRIVEN_INTERACTORS/DataDrivenInteractors.net
/usr/local/dx/samples/programs/DATA_DRIVEN_INTERACTORS/DataDrivenSelector.cfg
/usr/local/dx/samples/programs/DATA_DRIVEN_INTERACTORS/DataDrivenSelector.net
/usr/local/dx/samples/programs/DATA_DRIVEN_INTERACTORS/Imide_potential.cfg
/usr/local/dx/samples/programs/DATA_DRIVEN_INTERACTORS/Imide_potential.net
%dir /usr/local/dx/samples/programs/DEBUGGING/
/usr/local/dx/samples/programs/DEBUGGING/Verify.cfg
/usr/local/dx/samples/programs/DEBUGGING/Verify.net
/usr/local/dx/samples/programs/DEBUGGING/VisualObject.cfg
/usr/local/dx/samples/programs/DEBUGGING/VisualObject.net
%dir /usr/local/dx/samples/programs/DISTRIBUTED_PROCESSING/
/usr/local/dx/samples/programs/DISTRIBUTED_PROCESSING/Distributed.cfg
/usr/local/dx/samples/programs/DISTRIBUTED_PROCESSING/Distributed.net
%dir /usr/local/dx/samples/programs/IMAGE_PROCESSING/
/usr/local/dx/samples/programs/IMAGE_PROCESSING/FFT.cfg
/usr/local/dx/samples/programs/IMAGE_PROCESSING/FFT.net
/usr/local/dx/samples/programs/IMAGE_PROCESSING/MRI_1.cfg
/usr/local/dx/samples/programs/IMAGE_PROCESSING/MRI_1.net
/usr/local/dx/samples/programs/IMAGE_PROCESSING/QuantizeImage.cfg
/usr/local/dx/samples/programs/IMAGE_PROCESSING/QuantizeImage.net
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingEqualize.cfg
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingEqualize.net
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingFilter.cfg
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingFilter.net
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingMorph.cfg
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingMorph.net
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingOverlay.cfg
/usr/local/dx/samples/programs/IMAGE_PROCESSING/UsingOverlay.net
%dir /usr/local/dx/samples/programs/IMPORTING/
/usr/local/dx/samples/programs/IMPORTING/Categorical.cfg
/usr/local/dx/samples/programs/IMPORTING/Categorical.net
/usr/local/dx/samples/programs/IMPORTING/Duplicates.cfg
/usr/local/dx/samples/programs/IMPORTING/Duplicates.net
/usr/local/dx/samples/programs/IMPORTING/GeneralImport1.cfg
/usr/local/dx/samples/programs/IMPORTING/GeneralImport1.net
/usr/local/dx/samples/programs/IMPORTING/GeneralImport2.cfg
/usr/local/dx/samples/programs/IMPORTING/GeneralImport2.net
/usr/local/dx/samples/programs/IMPORTING/ImportExternalFilter.cfg
/usr/local/dx/samples/programs/IMPORTING/ImportExternalFilter.net
/usr/local/dx/samples/programs/IMPORTING/ZipCodes.cfg
/usr/local/dx/samples/programs/IMPORTING/ZipCodes.net
%dir /usr/local/dx/samples/programs/INTERFACE_CONTROL/
/usr/local/dx/samples/programs/INTERFACE_CONTROL/DialogStyle.cfg
/usr/local/dx/samples/programs/INTERFACE_CONTROL/DialogStyle.net
/usr/local/dx/samples/programs/INTERFACE_CONTROL/InterfaceControl1.cfg
/usr/local/dx/samples/programs/INTERFACE_CONTROL/InterfaceControl1.net
/usr/local/dx/samples/programs/INTERFACE_CONTROL/InterfaceControl2.cfg
/usr/local/dx/samples/programs/INTERFACE_CONTROL/InterfaceControl2.net
/usr/local/dx/samples/programs/INTERFACE_CONTROL/InterfaceControl3.cfg
/usr/local/dx/samples/programs/INTERFACE_CONTROL/InterfaceControl3.net
%dir /usr/local/dx/samples/programs/LOOPING/
/usr/local/dx/samples/programs/LOOPING/Accumulate.cfg
/usr/local/dx/samples/programs/LOOPING/Accumulate.net
/usr/local/dx/samples/programs/LOOPING/Bounce.cfg
/usr/local/dx/samples/programs/LOOPING/Bounce.net
/usr/local/dx/samples/programs/LOOPING/SimpleGetSetLoop.cfg
/usr/local/dx/samples/programs/LOOPING/SimpleGetSetLoop.net
%dir /usr/local/dx/samples/programs/MISC/
/usr/local/dx/samples/programs/MISC/CensusData.cfg
/usr/local/dx/samples/programs/MISC/CensusData.net
/usr/local/dx/samples/programs/MISC/ExampleSMP.cfg
/usr/local/dx/samples/programs/MISC/ExampleSMP.net
/usr/local/dx/samples/programs/MISC/Factorial.cfg
/usr/local/dx/samples/programs/MISC/Factorial.net
/usr/local/dx/samples/programs/MISC/HomeOwn.cfg
/usr/local/dx/samples/programs/MISC/HomeOwn.net
/usr/local/dx/samples/programs/MISC/ImageTool.cfg
/usr/local/dx/samples/programs/MISC/ImageTool.net
/usr/local/dx/samples/programs/MISC/Image_wo_UI.cfg
/usr/local/dx/samples/programs/MISC/Image_wo_UI.net
/usr/local/dx/samples/programs/MISC/IndependentlyArrange.cfg
/usr/local/dx/samples/programs/MISC/IndependentlyArrange.net
/usr/local/dx/samples/programs/MISC/InsetImage.cfg
/usr/local/dx/samples/programs/MISC/InsetImage.net
/usr/local/dx/samples/programs/MISC/Interop.cfg
/usr/local/dx/samples/programs/MISC/Interop.net
/usr/local/dx/samples/programs/MISC/InvalidData.cfg
/usr/local/dx/samples/programs/MISC/InvalidData.net
/usr/local/dx/samples/programs/MISC/MRI_1.cfg
/usr/local/dx/samples/programs/MISC/MRI_1.net
/usr/local/dx/samples/programs/MISC/MRI_2.cfg
/usr/local/dx/samples/programs/MISC/MRI_2.net
/usr/local/dx/samples/programs/MISC/Majority.cfg
/usr/local/dx/samples/programs/MISC/Majority.net
/usr/local/dx/samples/programs/MISC/ManipulateGroups.cfg
/usr/local/dx/samples/programs/MISC/ManipulateGroups.net
/usr/local/dx/samples/programs/MISC/MultipleDataSets.cfg
/usr/local/dx/samples/programs/MISC/MultipleDataSets.net
/usr/local/dx/samples/programs/MISC/PickStreamline.cfg
/usr/local/dx/samples/programs/MISC/PickStreamline.net
/usr/local/dx/samples/programs/MISC/ScatterData.cfg
/usr/local/dx/samples/programs/MISC/ScatterData.net
/usr/local/dx/samples/programs/MISC/Supervise.cfg
/usr/local/dx/samples/programs/MISC/Supervise.net
/usr/local/dx/samples/programs/MISC/Topo.cfg
/usr/local/dx/samples/programs/MISC/Topo.net
/usr/local/dx/samples/programs/MISC/UsingAttributes.cfg
/usr/local/dx/samples/programs/MISC/UsingAttributes.net
/usr/local/dx/samples/programs/MISC/UsingDrape.cfg
/usr/local/dx/samples/programs/MISC/UsingDrape.net
/usr/local/dx/samples/programs/MISC/UsingEqualize.cfg
/usr/local/dx/samples/programs/MISC/UsingEqualize.net
/usr/local/dx/samples/programs/MISC/UsingMessage.cfg
/usr/local/dx/samples/programs/MISC/UsingMessage.net
/usr/local/dx/samples/programs/MISC/UsingMultiGrids.cfg
/usr/local/dx/samples/programs/MISC/UsingMultiGrids.net
/usr/local/dx/samples/programs/MISC/UsingParse.cfg
/usr/local/dx/samples/programs/MISC/UsingParse.net
/usr/local/dx/samples/programs/MISC/UsingSwitchAndRoute.cfg
/usr/local/dx/samples/programs/MISC/UsingSwitchAndRoute.net
%dir /usr/local/dx/samples/programs/PLOTTING/
/usr/local/dx/samples/programs/PLOTTING/Categorical.cfg
/usr/local/dx/samples/programs/PLOTTING/Categorical.net
/usr/local/dx/samples/programs/PLOTTING/GroceryList.cfg
/usr/local/dx/samples/programs/PLOTTING/GroceryList.net
/usr/local/dx/samples/programs/PLOTTING/Histogram.cfg
/usr/local/dx/samples/programs/PLOTTING/Histogram.net
/usr/local/dx/samples/programs/PLOTTING/InterfaceControl2.cfg
/usr/local/dx/samples/programs/PLOTTING/InterfaceControl2.net
/usr/local/dx/samples/programs/PLOTTING/PickPlot.cfg
/usr/local/dx/samples/programs/PLOTTING/PickPlot.net
/usr/local/dx/samples/programs/PLOTTING/PlotGroupOfLines.cfg
/usr/local/dx/samples/programs/PLOTTING/PlotGroupOfLines.net
/usr/local/dx/samples/programs/PLOTTING/PlotLine.cfg
/usr/local/dx/samples/programs/PLOTTING/PlotLine.net
/usr/local/dx/samples/programs/PLOTTING/PlotLine2.cfg
/usr/local/dx/samples/programs/PLOTTING/PlotLine2.net
/usr/local/dx/samples/programs/PLOTTING/PlotSpecifyTicks.cfg
/usr/local/dx/samples/programs/PLOTTING/PlotSpecifyTicks.net
/usr/local/dx/samples/programs/PLOTTING/PlotTwoLines.cfg
/usr/local/dx/samples/programs/PLOTTING/PlotTwoLines.net
/usr/local/dx/samples/programs/PLOTTING/Sort.cfg
/usr/local/dx/samples/programs/PLOTTING/Sort.net
/usr/local/dx/samples/programs/PLOTTING/UsingBarChart.cfg
/usr/local/dx/samples/programs/PLOTTING/UsingBarChart.net
/usr/local/dx/samples/programs/PLOTTING/UsingEqualize.cfg
/usr/local/dx/samples/programs/PLOTTING/UsingEqualize.net
%dir /usr/local/dx/samples/programs/PROBES/
/usr/local/dx/samples/programs/PROBES/PlotLine2.cfg
/usr/local/dx/samples/programs/PROBES/PlotLine2.net
/usr/local/dx/samples/programs/PROBES/ProbeText.cfg
/usr/local/dx/samples/programs/PROBES/ProbeText.net
/usr/local/dx/samples/programs/PROBES/UsingProbes.cfg
/usr/local/dx/samples/programs/PROBES/UsingProbes.net
/usr/local/dx/samples/programs/PROBES/UsingStreakline.cfg
/usr/local/dx/samples/programs/PROBES/UsingStreakline.net
%dir /usr/local/dx/samples/programs/RENDERING/
/usr/local/dx/samples/programs/RENDERING/FatLines.cfg
/usr/local/dx/samples/programs/RENDERING/FatLines.net
/usr/local/dx/samples/programs/RENDERING/Isolate.cfg
/usr/local/dx/samples/programs/RENDERING/Isolate.net
/usr/local/dx/samples/programs/RENDERING/SharedCamera.cfg
/usr/local/dx/samples/programs/RENDERING/SharedCamera.net
/usr/local/dx/samples/programs/RENDERING/TextureMapOpenGL.cfg
/usr/local/dx/samples/programs/RENDERING/TextureMapOpenGL.net
/usr/local/dx/samples/programs/RENDERING/UsingClipPlane.cfg
/usr/local/dx/samples/programs/RENDERING/UsingClipPlane.net
/usr/local/dx/samples/programs/RENDERING/UsingLights.cfg
/usr/local/dx/samples/programs/RENDERING/UsingLights.net
/usr/local/dx/samples/programs/RENDERING/UsingShade.cfg
/usr/local/dx/samples/programs/RENDERING/UsingShade.net
/usr/local/dx/samples/programs/RENDERING/VolumeRendering.cfg
/usr/local/dx/samples/programs/RENDERING/VolumeRendering.net
/usr/local/dx/samples/programs/RENDERING/VolumeRenderingSimple.cfg
/usr/local/dx/samples/programs/RENDERING/VolumeRenderingSimple.net
%dir /usr/local/dx/samples/programs/SCATTERED/
/usr/local/dx/samples/programs/SCATTERED/AnnotationGlyphs.cfg
/usr/local/dx/samples/programs/SCATTERED/AnnotationGlyphs.net
/usr/local/dx/samples/programs/SCATTERED/ConnectingScatteredPoints.cfg
/usr/local/dx/samples/programs/SCATTERED/ConnectingScatteredPoints.net
/usr/local/dx/samples/programs/SCATTERED/ScatterData.cfg
/usr/local/dx/samples/programs/SCATTERED/ScatterData.net
%dir /usr/local/dx/samples/programs/SEQUENCER/
/usr/local/dx/samples/programs/SEQUENCER/ContoursAndCaption.cfg
/usr/local/dx/samples/programs/SEQUENCER/ContoursAndCaption.net
/usr/local/dx/samples/programs/SEQUENCER/FlyThrough.cfg
/usr/local/dx/samples/programs/SEQUENCER/FlyThrough.net
/usr/local/dx/samples/programs/SEQUENCER/FlyThrough2.cfg
/usr/local/dx/samples/programs/SEQUENCER/FlyThrough2.net
/usr/local/dx/samples/programs/SEQUENCER/Imide_potential.cfg
/usr/local/dx/samples/programs/SEQUENCER/Imide_potential.net
/usr/local/dx/samples/programs/SEQUENCER/MRI_1.cfg
/usr/local/dx/samples/programs/SEQUENCER/MRI_1.net
/usr/local/dx/samples/programs/SEQUENCER/MovingCamera.cfg
/usr/local/dx/samples/programs/SEQUENCER/MovingCamera.net
/usr/local/dx/samples/programs/SEQUENCER/MovingSheet.cfg
/usr/local/dx/samples/programs/SEQUENCER/MovingSheet.net
/usr/local/dx/samples/programs/SEQUENCER/Sort.cfg
/usr/local/dx/samples/programs/SEQUENCER/Sort.net
/usr/local/dx/samples/programs/SEQUENCER/SpecialCharacters.cfg
/usr/local/dx/samples/programs/SEQUENCER/SpecialCharacters.net
/usr/local/dx/samples/programs/SEQUENCER/Streamline.cfg
/usr/local/dx/samples/programs/SEQUENCER/Streamline.net
%dir /usr/local/dx/samples/programs/SIMPLE/
/usr/local/dx/samples/programs/SIMPLE/Arrange.cfg
/usr/local/dx/samples/programs/SIMPLE/Arrange.net
/usr/local/dx/samples/programs/SIMPLE/AutoAxes.cfg
/usr/local/dx/samples/programs/SIMPLE/AutoAxes.net
/usr/local/dx/samples/programs/SIMPLE/AutoColor.cfg
/usr/local/dx/samples/programs/SIMPLE/AutoColor.net
/usr/local/dx/samples/programs/SIMPLE/AutoGlyph.cfg
/usr/local/dx/samples/programs/SIMPLE/AutoGlyph.net
/usr/local/dx/samples/programs/SIMPLE/AutoGrid.cfg
/usr/local/dx/samples/programs/SIMPLE/AutoGrid.net
/usr/local/dx/samples/programs/SIMPLE/Band.cfg
/usr/local/dx/samples/programs/SIMPLE/Band.net
/usr/local/dx/samples/programs/SIMPLE/Caption.cfg
/usr/local/dx/samples/programs/SIMPLE/Caption.net
/usr/local/dx/samples/programs/SIMPLE/Color.cfg
/usr/local/dx/samples/programs/SIMPLE/Color.net
/usr/local/dx/samples/programs/SIMPLE/ColorBar.cfg
/usr/local/dx/samples/programs/SIMPLE/ColorBar.net
/usr/local/dx/samples/programs/SIMPLE/Compute2.cfg
/usr/local/dx/samples/programs/SIMPLE/Compute2.net
/usr/local/dx/samples/programs/SIMPLE/Connect.cfg
/usr/local/dx/samples/programs/SIMPLE/Connect.net
/usr/local/dx/samples/programs/SIMPLE/Construct.cfg
/usr/local/dx/samples/programs/SIMPLE/Construct.net
/usr/local/dx/samples/programs/SIMPLE/Describe.cfg
/usr/local/dx/samples/programs/SIMPLE/Describe.net
/usr/local/dx/samples/programs/SIMPLE/FaceNormals.cfg
/usr/local/dx/samples/programs/SIMPLE/FaceNormals.net
/usr/local/dx/samples/programs/SIMPLE/GetSet.cfg
/usr/local/dx/samples/programs/SIMPLE/GetSet.net
/usr/local/dx/samples/programs/SIMPLE/Gradient.cfg
/usr/local/dx/samples/programs/SIMPLE/Gradient.net
/usr/local/dx/samples/programs/SIMPLE/Grid.cfg
/usr/local/dx/samples/programs/SIMPLE/Grid.net
/usr/local/dx/samples/programs/SIMPLE/Histogram.cfg
/usr/local/dx/samples/programs/SIMPLE/Histogram.net
/usr/local/dx/samples/programs/SIMPLE/Include.cfg
/usr/local/dx/samples/programs/SIMPLE/Include.net
/usr/local/dx/samples/programs/SIMPLE/Isolate.cfg
/usr/local/dx/samples/programs/SIMPLE/Isolate.net
/usr/local/dx/samples/programs/SIMPLE/Isosurface.cfg
/usr/local/dx/samples/programs/SIMPLE/Isosurface.net
/usr/local/dx/samples/programs/SIMPLE/Light.cfg
/usr/local/dx/samples/programs/SIMPLE/Light.net
/usr/local/dx/samples/programs/SIMPLE/Map.cfg
/usr/local/dx/samples/programs/SIMPLE/Map.net
/usr/local/dx/samples/programs/SIMPLE/MapToPlane.cfg
/usr/local/dx/samples/programs/SIMPLE/MapToPlane.net
/usr/local/dx/samples/programs/SIMPLE/MarkUnmark.cfg
/usr/local/dx/samples/programs/SIMPLE/MarkUnmark.net
/usr/local/dx/samples/programs/SIMPLE/Post.cfg
/usr/local/dx/samples/programs/SIMPLE/Post.net
/usr/local/dx/samples/programs/SIMPLE/QuantizeImage.cfg
/usr/local/dx/samples/programs/SIMPLE/QuantizeImage.net
/usr/local/dx/samples/programs/SIMPLE/Reduce.cfg
/usr/local/dx/samples/programs/SIMPLE/Reduce.net
/usr/local/dx/samples/programs/SIMPLE/Refine.cfg
/usr/local/dx/samples/programs/SIMPLE/Refine.net
/usr/local/dx/samples/programs/SIMPLE/Regrid.cfg
/usr/local/dx/samples/programs/SIMPLE/Regrid.net
/usr/local/dx/samples/programs/SIMPLE/Route.cfg
/usr/local/dx/samples/programs/SIMPLE/Route.net
/usr/local/dx/samples/programs/SIMPLE/Rubbersheet.cfg
/usr/local/dx/samples/programs/SIMPLE/Rubbersheet.net
/usr/local/dx/samples/programs/SIMPLE/ScaleScreen.cfg
/usr/local/dx/samples/programs/SIMPLE/ScaleScreen.net
/usr/local/dx/samples/programs/SIMPLE/ShowBoundary.cfg
/usr/local/dx/samples/programs/SIMPLE/ShowBoundary.net
/usr/local/dx/samples/programs/SIMPLE/Slab.cfg
/usr/local/dx/samples/programs/SIMPLE/Slab.net
/usr/local/dx/samples/programs/SIMPLE/Sort.cfg
/usr/local/dx/samples/programs/SIMPLE/Sort.net
/usr/local/dx/samples/programs/SIMPLE/Streamline.cfg
/usr/local/dx/samples/programs/SIMPLE/Streamline.net
/usr/local/dx/samples/programs/SIMPLE/Supervise.cfg
/usr/local/dx/samples/programs/SIMPLE/Supervise.net
/usr/local/dx/samples/programs/SIMPLE/Switch.cfg
/usr/local/dx/samples/programs/SIMPLE/Switch.net
/usr/local/dx/samples/programs/SIMPLE/Verify.cfg
/usr/local/dx/samples/programs/SIMPLE/Verify.net
/usr/local/dx/samples/programs/SIMPLE/VisualObject.cfg
/usr/local/dx/samples/programs/SIMPLE/VisualObject.net
%dir /usr/local/dx/samples/programs/SUPERVISE/
/usr/local/dx/samples/programs/SUPERVISE/Image_wo_UI.cfg
/usr/local/dx/samples/programs/SUPERVISE/Image_wo_UI.net
/usr/local/dx/samples/programs/SUPERVISE/IndependentlyArrange.cfg
/usr/local/dx/samples/programs/SUPERVISE/IndependentlyArrange.net
/usr/local/dx/samples/programs/SUPERVISE/InsetImage.cfg
/usr/local/dx/samples/programs/SUPERVISE/InsetImage.net
/usr/local/dx/samples/programs/SUPERVISE/InsetImageSimple.cfg
/usr/local/dx/samples/programs/SUPERVISE/InsetImageSimple.net
/usr/local/dx/samples/programs/SUPERVISE/Supervise.cfg
/usr/local/dx/samples/programs/SUPERVISE/Supervise.net
/usr/local/dx/samples/programs/SUPERVISE/SupervisePicking.cfg
/usr/local/dx/samples/programs/SUPERVISE/SupervisePicking.net
%dir /usr/local/dx/samples/scripts/
/usr/local/dx/samples/scripts/AmbientLight
/usr/local/dx/samples/scripts/Append
/usr/local/dx/samples/scripts/Arrange
/usr/local/dx/samples/scripts/Attribute
/usr/local/dx/samples/scripts/AutoAxes
/usr/local/dx/samples/scripts/AutoCamera
/usr/local/dx/samples/scripts/AutoColor
/usr/local/dx/samples/scripts/AutoGlyph
/usr/local/dx/samples/scripts/AutoGrayScale
/usr/local/dx/samples/scripts/Band
/usr/local/dx/samples/scripts/Camera
/usr/local/dx/samples/scripts/Caption
/usr/local/dx/samples/scripts/ClipBox
/usr/local/dx/samples/scripts/ClipPlane
/usr/local/dx/samples/scripts/Collect
/usr/local/dx/samples/scripts/CollectMultiGrid
/usr/local/dx/samples/scripts/CollectNamed
/usr/local/dx/samples/scripts/CollectSeries
/usr/local/dx/samples/scripts/Color
/usr/local/dx/samples/scripts/ColorBar
/usr/local/dx/samples/scripts/Compute
/usr/local/dx/samples/scripts/Compute2
/usr/local/dx/samples/scripts/Connect
/usr/local/dx/samples/scripts/Construct
/usr/local/dx/samples/scripts/Convert
/usr/local/dx/samples/scripts/Direction
/usr/local/dx/samples/scripts/Display
/usr/local/dx/samples/scripts/DivCurl
/usr/local/dx/samples/scripts/Echo
/usr/local/dx/samples/scripts/Enumerate
/usr/local/dx/samples/scripts/Equalize
/usr/local/dx/samples/scripts/Export
/usr/local/dx/samples/scripts/Extract
/usr/local/dx/samples/scripts/FaceNormals
/usr/local/dx/samples/scripts/Filter
/usr/local/dx/samples/scripts/Format
/usr/local/dx/samples/scripts/GetSet
/usr/local/dx/samples/scripts/Glyph
/usr/local/dx/samples/scripts/Gradient
/usr/local/dx/samples/scripts/Grid
/usr/local/dx/samples/scripts/Histogram
/usr/local/dx/samples/scripts/Include
/usr/local/dx/samples/scripts/Inquire
/usr/local/dx/samples/scripts/Isosurface
/usr/local/dx/samples/scripts/KeyIn
/usr/local/dx/samples/scripts/Light
/usr/local/dx/samples/scripts/List
/usr/local/dx/samples/scripts/Map
/usr/local/dx/samples/scripts/MapToPlane
/usr/local/dx/samples/scripts/Mark
/usr/local/dx/samples/scripts/Measure
/usr/local/dx/samples/scripts/Morph
/usr/local/dx/samples/scripts/Normals
/usr/local/dx/samples/scripts/Options
/usr/local/dx/samples/scripts/Overlay
/usr/local/dx/samples/scripts/Partition
/usr/local/dx/samples/scripts/Plot
/usr/local/dx/samples/scripts/Post
/usr/local/dx/samples/scripts/Print
/usr/local/dx/samples/scripts/ReadImage
%doc /usr/local/dx/samples/scripts/Readme
/usr/local/dx/samples/scripts/Reduce
/usr/local/dx/samples/scripts/Refine
/usr/local/dx/samples/scripts/Regrid
/usr/local/dx/samples/scripts/Remove
/usr/local/dx/samples/scripts/Rename
/usr/local/dx/samples/scripts/Render
/usr/local/dx/samples/scripts/Replace
/usr/local/dx/samples/scripts/Ribbon
/usr/local/dx/samples/scripts/Rotate
/usr/local/dx/samples/scripts/Route
/usr/local/dx/samples/scripts/RubberSheet
/usr/local/dx/samples/scripts/Sample
/usr/local/dx/samples/scripts/Scale
/usr/local/dx/samples/scripts/Select
/usr/local/dx/samples/scripts/Sequencer
/usr/local/dx/samples/scripts/Shade
/usr/local/dx/samples/scripts/ShowBoundary
/usr/local/dx/samples/scripts/ShowBox
/usr/local/dx/samples/scripts/ShowConnections
/usr/local/dx/samples/scripts/ShowPositions
/usr/local/dx/samples/scripts/Slab
/usr/local/dx/samples/scripts/Slice
/usr/local/dx/samples/scripts/Sort
/usr/local/dx/samples/scripts/Stack
/usr/local/dx/samples/scripts/Statistics
/usr/local/dx/samples/scripts/Streakline
/usr/local/dx/samples/scripts/Streamline
/usr/local/dx/samples/scripts/Supervise
/usr/local/dx/samples/scripts/Switch
/usr/local/dx/samples/scripts/System
/usr/local/dx/samples/scripts/Text
/usr/local/dx/samples/scripts/Transform
/usr/local/dx/samples/scripts/Translate
/usr/local/dx/samples/scripts/Transpose
/usr/local/dx/samples/scripts/Tube
/usr/local/dx/samples/scripts/Unmark
/usr/local/dx/samples/scripts/Usage
/usr/local/dx/samples/scripts/Verify
/usr/local/dx/samples/scripts/WriteImage
/usr/local/dx/samples/scripts/interop
/usr/local/dx/samples/scripts/scriptexample
%dir /usr/local/dx/samples/supervise/
%dir /usr/local/dx/samples/supervise/complexdemo/
%dir /usr/local/dx/samples/supervise/complexdemo/data/
/usr/local/dx/samples/supervise/complexdemo/data/frags.dx
%dir /usr/local/dx/samples/supervise/complexdemo/interactors/
/usr/local/dx/samples/supervise/complexdemo/interactors/Makefile_alphax
/usr/local/dx/samples/supervise/complexdemo/interactors/Makefile_hp700
/usr/local/dx/samples/supervise/complexdemo/interactors/Makefile_ibm6000
/usr/local/dx/samples/supervise/complexdemo/interactors/Makefile_sgi
/usr/local/dx/samples/supervise/complexdemo/interactors/Makefile_solaris
/usr/local/dx/samples/supervise/complexdemo/interactors/interactors.c
/usr/local/dx/samples/supervise/complexdemo/interactors/module_make
/usr/local/dx/samples/supervise/complexdemo/interactors/Makefile
%dir /usr/local/dx/samples/supervise/complexdemo/nets/
/usr/local/dx/samples/supervise/complexdemo/nets/ShowSelected.net
/usr/local/dx/samples/supervise/complexdemo/nets/hiliteObject.net
/usr/local/dx/samples/supervise/complexdemo/nets/peruDX.cfg
/usr/local/dx/samples/supervise/complexdemo/nets/peruDX.net
%doc /usr/local/dx/samples/supervise/complexdemo/ReadMe
/usr/local/dx/samples/supervise/complexdemo/demo
%dir /usr/local/dx/samples/supervise/imagedemo/
%doc /usr/local/dx/samples/supervise/imagedemo/ReadMe
/usr/local/dx/samples/supervise/imagedemo/demo
/usr/local/dx/samples/supervise/imagedemo/demo.cfg
/usr/local/dx/samples/supervise/imagedemo/demo.net
/usr/local/dx/samples/supervise/imagedemo/demo1
/usr/local/dx/samples/supervise/imagedemo/demo1.cfg
/usr/local/dx/samples/supervise/imagedemo/demo1.net
%dir /usr/local/dx/samples/supervise/interactors/
/usr/local/dx/samples/supervise/interactors/Makefile_alphax
/usr/local/dx/samples/supervise/interactors/Makefile_aviion
/usr/local/dx/samples/supervise/interactors/Makefile_hp700
/usr/local/dx/samples/supervise/interactors/Makefile_ibm6000
/usr/local/dx/samples/supervise/interactors/Makefile_sgi
/usr/local/dx/samples/supervise/interactors/Makefile_solaris
/usr/local/dx/samples/supervise/interactors/Makefile_sun4
%doc /usr/local/dx/samples/supervise/interactors/ReadMe
/usr/local/dx/samples/supervise/interactors/myinteractors.c
/usr/local/dx/samples/supervise/interactors/module_make
/usr/local/dx/samples/supervise/interactors/Makefile
%dir /usr/local/dx/samples/supervise/mediumdemo/
%dir /usr/local/dx/samples/supervise/mediumdemo/interactors/
/usr/local/dx/samples/supervise/mediumdemo/interactors/Makefile_alphax
/usr/local/dx/samples/supervise/mediumdemo/interactors/Makefile_hp700
/usr/local/dx/samples/supervise/mediumdemo/interactors/Makefile_ibm6000
/usr/local/dx/samples/supervise/mediumdemo/interactors/Makefile_sgi
/usr/local/dx/samples/supervise/mediumdemo/interactors/Makefile_solaris
/usr/local/dx/samples/supervise/mediumdemo/interactors/interactors.c
/usr/local/dx/samples/supervise/mediumdemo/interactors/module_make
/usr/local/dx/samples/supervise/mediumdemo/interactors/Makefile
%doc /usr/local/dx/samples/supervise/mediumdemo/ReadMe
/usr/local/dx/samples/supervise/mediumdemo/demo
%dir /usr/local/dx/samples/supervise/simpledemo/
%dir /usr/local/dx/samples/supervise/simpledemo/interactors/
/usr/local/dx/samples/supervise/simpledemo/interactors/Makefile_alphax
/usr/local/dx/samples/supervise/simpledemo/interactors/Makefile_hp700
/usr/local/dx/samples/supervise/simpledemo/interactors/Makefile_ibm6000
/usr/local/dx/samples/supervise/simpledemo/interactors/Makefile_sgi
/usr/local/dx/samples/supervise/simpledemo/interactors/Makefile_solaris
/usr/local/dx/samples/supervise/simpledemo/interactors/interactors.c
/usr/local/dx/samples/supervise/simpledemo/interactors/module_make
/usr/local/dx/samples/supervise/simpledemo/interactors/Makefile
%doc /usr/local/dx/samples/supervise/simpledemo/ReadMe
/usr/local/dx/samples/supervise/simpledemo/demo
/usr/local/dx/samples/supervise/simpledemo/demo.cfg
/usr/local/dx/samples/supervise/simpledemo/demo.net
%dir /usr/local/dx/samples/tutorial/
/usr/local/dx/samples/tutorial/Animate.cfg
/usr/local/dx/samples/tutorial/Animate.net
/usr/local/dx/samples/tutorial/AutoColor.cfg
/usr/local/dx/samples/tutorial/AutoColor.net
/usr/local/dx/samples/tutorial/AutoColor2D.cfg
/usr/local/dx/samples/tutorial/AutoColor2D.net
/usr/local/dx/samples/tutorial/AutoGlyph2DScalar.cfg
/usr/local/dx/samples/tutorial/AutoGlyph2DScalar.net
/usr/local/dx/samples/tutorial/AutoGlyph2DVector.cfg
/usr/local/dx/samples/tutorial/AutoGlyph2DVector.net
/usr/local/dx/samples/tutorial/AutoGlyph3DScalar.cfg
/usr/local/dx/samples/tutorial/AutoGlyph3DScalar.net
/usr/local/dx/samples/tutorial/AutoGlyph3DVector.cfg
/usr/local/dx/samples/tutorial/AutoGlyph3DVector.net
/usr/local/dx/samples/tutorial/Caption.cfg
/usr/local/dx/samples/tutorial/Caption.net
/usr/local/dx/samples/tutorial/Color2D.cfg
/usr/local/dx/samples/tutorial/Color2D.net
/usr/local/dx/samples/tutorial/Compute.cfg
/usr/local/dx/samples/tutorial/Compute.net
/usr/local/dx/samples/tutorial/Connect.cfg
/usr/local/dx/samples/tutorial/Connect.net
/usr/local/dx/samples/tutorial/DataDrivenColormap.cfg
/usr/local/dx/samples/tutorial/DataDrivenColormap.net
/usr/local/dx/samples/tutorial/DataDrivenScalar.cfg
/usr/local/dx/samples/tutorial/DataDrivenScalar.net
/usr/local/dx/samples/tutorial/DataDrivenSelector.cfg
/usr/local/dx/samples/tutorial/DataDrivenSelector.net
/usr/local/dx/samples/tutorial/DataDrivenSequencer.cfg
/usr/local/dx/samples/tutorial/DataDrivenSequencer.net
/usr/local/dx/samples/tutorial/ImageProcessing.cfg
/usr/local/dx/samples/tutorial/ImageProcessing.net
/usr/local/dx/samples/tutorial/Isosurface2D.cfg
/usr/local/dx/samples/tutorial/Isosurface2D.net
/usr/local/dx/samples/tutorial/Isosurface3D.cfg
/usr/local/dx/samples/tutorial/Isosurface3D.net
/usr/local/dx/samples/tutorial/Map.cfg
/usr/local/dx/samples/tutorial/Map.net
/usr/local/dx/samples/tutorial/Plot.cfg
/usr/local/dx/samples/tutorial/MapToPlane.cfg
/usr/local/dx/samples/tutorial/MapToPlane.net
/usr/local/dx/samples/tutorial/Plot.net
/usr/local/dx/samples/tutorial/Regrid.cfg
/usr/local/dx/samples/tutorial/Regrid.net
/usr/local/dx/samples/tutorial/RubberSheet.cfg
/usr/local/dx/samples/tutorial/RubberSheet.net
/usr/local/dx/samples/tutorial/SampleMacro.net
/usr/local/dx/samples/tutorial/Slab.cfg
/usr/local/dx/samples/tutorial/Slab.net
/usr/local/dx/samples/tutorial/Streamlines2D.cfg
/usr/local/dx/samples/tutorial/Streamlines2D.net
/usr/local/dx/samples/tutorial/Streamlines3D.cfg
/usr/local/dx/samples/tutorial/Streamlines3D.net
/usr/local/dx/samples/tutorial/Switch.cfg
/usr/local/dx/samples/tutorial/Switch.net
/usr/local/dx/samples/tutorial/UseSampleMacro.cfg
/usr/local/dx/samples/tutorial/UseSampleMacro.net
/usr/local/dx/samples/tutorial/VolumeRendering.cfg
/usr/local/dx/samples/tutorial/VolumeRendering.net
/usr/local/dx/samples/tutorial/WarpedGrid.cfg
/usr/local/dx/samples/tutorial/WarpedGrid.net
/usr/local/dx/samples/tutorial/batch_script
/usr/local/dx/samples/tutorial/example.general
/usr/local/dx/samples/tutorial/example1.cfg
/usr/local/dx/samples/tutorial/example1.net
/usr/local/dx/samples/tutorial/external.data
/usr/local/dx/samples/tutorial/spreadsheet.data
/usr/local/dx/samples/tutorial/view_isosurfaces.cfg
/usr/local/dx/samples/tutorial/view_isosurfaces.net
%dir /usr/local/dx/samples/user/
/usr/local/dx/samples/user/Makefile_inboard_alphax
/usr/local/dx/samples/user/Makefile_inboard_aviion
/usr/local/dx/samples/user/Makefile_inboard_hp700
/usr/local/dx/samples/user/Makefile_inboard_ibm6000
/usr/local/dx/samples/user/Makefile_inboard_ibmpvs
/usr/local/dx/samples/user/Makefile_inboard_intelnt
/usr/local/dx/samples/user/Makefile_inboard_sgi
/usr/local/dx/samples/user/Makefile_inboard_solaris
/usr/local/dx/samples/user/Makefile_inboard_sun4
/usr/local/dx/samples/user/Makefile_intelnt
/usr/local/dx/samples/user/Makefile_loadable_alphax
/usr/local/dx/samples/user/Makefile_loadable_hp700
/usr/local/dx/samples/user/Makefile_loadable_ibm6000
/usr/local/dx/samples/user/Makefile_loadable_intelnt
/usr/local/dx/samples/user/Makefile_loadable_sgi
/usr/local/dx/samples/user/Makefile_loadable_solaris
/usr/local/dx/samples/user/Makefile_os2
/usr/local/dx/samples/user/Makefile_outboard_alphax
/usr/local/dx/samples/user/Makefile_outboard_aviion
/usr/local/dx/samples/user/Makefile_outboard_hp700
/usr/local/dx/samples/user/Makefile_outboard_ibm6000
/usr/local/dx/samples/user/Makefile_outboard_ibmpvs
/usr/local/dx/samples/user/Makefile_outboard_intelnt
/usr/local/dx/samples/user/Makefile_outboard_sgi
/usr/local/dx/samples/user/Makefile_outboard_solaris
/usr/local/dx/samples/user/Makefile_outboard_sun4
%doc /usr/local/dx/samples/user/Readme
/usr/local/dx/samples/user/add.c
/usr/local/dx/samples/user/hello.c
/usr/local/dx/samples/user/hello_loadable.mdf
/usr/local/dx/samples/user/makex.c
/usr/local/dx/samples/user/user_inboard.mdf
/usr/local/dx/samples/user/user_loadable.mdf
/usr/local/dx/samples/user/user_outboard.mdf
%dir /usr/local/dx/samples/util/
%dir /usr/local/dx/samples/util/dxf/
/usr/local/dx/samples/util/dxf/MANIFEST
/usr/local/dx/samples/util/dxf/Makefile.sample
%doc /usr/local/dx/samples/util/dxf/README
/usr/local/dx/samples/util/dxf/balloon.dxf
/usr/local/dx/samples/util/dxf/colors.c
/usr/local/dx/samples/util/dxf/common.c
/usr/local/dx/samples/util/dxf/dx.c
/usr/local/dx/samples/util/dxf/dxf.c
/usr/local/dx/samples/util/dxf/dxf.h
/usr/local/dx/samples/util/dxf/dxf_r12.txt
/usr/local/dx/samples/util/dxf/entity.c
/usr/local/dx/samples/util/dxf/entity.h
/usr/local/dx/samples/util/dxf/header.c
/usr/local/dx/samples/util/dxf/ignored.c
/usr/local/dx/samples/util/dxf/output_funcs.c
/usr/local/dx/samples/util/dxf/read.c
/usr/local/dx/samples/util/dxf/snag_funcs.c
/usr/local/dx/samples/util/dxf/table.c
/usr/local/dx/samples/util/dxf/tree.c
/usr/local/dx/samples/util/dxf/x29.dxf
%dir /usr/local/dx/samples/util/fluent/
/usr/local/dx/samples/util/fluent/Fluent2DX.c
%doc /usr/local/dx/samples/util/fluent/README
%dir /usr/local/dx/samples/util/mpeg/
%doc /usr/local/dx/samples/util/mpeg/README
/usr/local/dx/samples/util/mpeg/default.param
/usr/local/dx/samples/util/mpeg/write_yuv.cfg
/usr/local/dx/samples/util/mpeg/write_yuv.net
%dir /usr/local/dx/samples/util/plot3d/
/usr/local/dx/samples/util/plot3d/Plot3DtoDX.c
%doc /usr/local/dx/samples/util/plot3d/README
/usr/local/dx/samples/util/Makefile.sample
%dir /usr/local/dx/java/
%dir /usr/local/dx/java/server/
%dir /usr/local/dx/java/server/userdata/
/usr/local/dx/java/server/userdata/AutoInsurance.txt
/usr/local/dx/java/server/userdata/CCAll.dx
/usr/local/dx/java/server/userdata/Makefile.am
/usr/local/dx/java/server/userdata/Norm.dx
/usr/local/dx/java/server/userdata/apt.txt
/usr/local/dx/java/server/userdata/arf.txt
/usr/local/dx/java/server/userdata/asr.txt
/usr/local/dx/java/server/userdata/enhigh.cxn
/usr/local/dx/java/server/userdata/enhigh.txt
/usr/local/dx/java/server/userdata/enlow.cxn
/usr/local/dx/java/server/userdata/enlow.txt
/usr/local/dx/java/server/userdata/ibm94.txt
/usr/local/dx/java/server/userdata/ibm95.txt
/usr/local/dx/java/server/userdata/ibm96.txt
/usr/local/dx/java/server/userdata/mf1.txt
/usr/local/dx/java/server/userdata/npvcall.cm
/usr/local/dx/java/server/userdata/npvcall2.cm
/usr/local/dx/java/server/userdata/option.cm
%dir /usr/local/dx/java/server/usermacros/
/usr/local/dx/java/server/usermacros/ClassifyMacro.net
/usr/local/dx/java/server/usermacros/Legend2Macro.net
/usr/local/dx/java/server/usermacros/MOSFromLongLat.net
/usr/local/dx/java/server/usermacros/Makefile.am
/usr/local/dx/java/server/usermacros/bschols.net
/usr/local/dx/java/server/usermacros/kmeansmacro.net
/usr/local/dx/java/server/usermacros/logn.net
/usr/local/dx/java/server/usermacros/optsurf.net
/usr/local/dx/java/server/usermacros/pdflogn.net
/usr/local/dx/java/server/usermacros/prunemac.net
/usr/local/dx/java/server/usermacros/vhwymac.net
%dir /usr/local/dx/java/server/nets/
/usr/local/dx/java/server/nets/AutoInsurance.cfg
/usr/local/dx/java/server/nets/AutoInsurance.net
/usr/local/dx/java/server/nets/CCNet2.cfg
/usr/local/dx/java/server/nets/CCNet2.net
/usr/local/dx/java/server/nets/GroceryList.cfg
/usr/local/dx/java/server/nets/GroceryList.net
/usr/local/dx/java/server/nets/HomeOwn.cfg
/usr/local/dx/java/server/nets/HomeOwn.net
/usr/local/dx/java/server/nets/MRI_2.cfg
/usr/local/dx/java/server/nets/MRI_2.net
/usr/local/dx/java/server/nets/MutualFund.cfg
/usr/local/dx/java/server/nets/MutualFund.net
/usr/local/dx/java/server/nets/Navigation.cfg
/usr/local/dx/java/server/nets/Navigation.net
/usr/local/dx/java/server/nets/ScatterData.cfg
/usr/local/dx/java/server/nets/ScatterData.net
/usr/local/dx/java/server/nets/Streamline.cfg
/usr/local/dx/java/server/nets/Streamline.net
/usr/local/dx/java/server/nets/ThunderGlyphSheet.cfg
/usr/local/dx/java/server/nets/ThunderGlyphSheet.net
/usr/local/dx/java/server/nets/Topo.cfg
/usr/local/dx/java/server/nets/Topo.net
/usr/local/dx/java/server/nets/ddi.cfg
/usr/local/dx/java/server/nets/ddi.net
/usr/local/dx/java/server/nets/gordon.cfg
/usr/local/dx/java/server/nets/gordon.net
/usr/local/dx/java/server/nets/hedge.cfg
/usr/local/dx/java/server/nets/hedge.net
/usr/local/dx/java/server/nets/ibmqw.cfg
/usr/local/dx/java/server/nets/ibmqw.net
/usr/local/dx/java/server/nets/npvcall.cfg
/usr/local/dx/java/server/nets/npvcall.net
/usr/local/dx/java/server/nets/optval.cfg
/usr/local/dx/java/server/nets/optval.net
/usr/local/dx/java/server/nets/wacc.cfg
/usr/local/dx/java/server/nets/wacc.net
%dir /usr/local/dx/java/htmlpages/
/usr/local/dx/java/htmlpages/samples.jar
/usr/local/dx/java/htmlpages/AutoInsurance.html
/usr/local/dx/java/htmlpages/AutoInsurance1.0.0.gif
/usr/local/dx/java/htmlpages/AutoInsurance2.0.0.gif
/usr/local/dx/java/htmlpages/AutoInsurance3.0.0.gif
/usr/local/dx/java/htmlpages/CCNet2.html
/usr/local/dx/java/htmlpages/CCNet23.0.0.gif
/usr/local/dx/java/htmlpages/CCNet24.0.0.gif
/usr/local/dx/java/htmlpages/CCNet25.0.0.gif
/usr/local/dx/java/htmlpages/Demo4.gif
/usr/local/dx/java/htmlpages/GroceryList.html
/usr/local/dx/java/htmlpages/GroceryList2.0.0.gif
/usr/local/dx/java/htmlpages/GroceryList3.0.0.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.0.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.1.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.2.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.3.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.4.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.5.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.6.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.7.gif
/usr/local/dx/java/htmlpages/GroceryList4.0.8.gif
/usr/local/dx/java/htmlpages/HomeOwn.html
/usr/local/dx/java/htmlpages/HomeOwn1.0.0.gif
/usr/local/dx/java/htmlpages/HomeOwn2.0.0.gif
/usr/local/dx/java/htmlpages/HomeOwn3.0.0.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.0.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.1.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.2.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.3.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.4.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.5.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.6.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.7.gif
/usr/local/dx/java/htmlpages/HomeOwn4.0.8.gif
/usr/local/dx/java/htmlpages/MRI_2.html
/usr/local/dx/java/htmlpages/MRI_21.0.0.gif
/usr/local/dx/java/htmlpages/MRI_22.0.0.gif
/usr/local/dx/java/htmlpages/MRI_22.0.1.gif
/usr/local/dx/java/htmlpages/MRI_22.0.2.gif
/usr/local/dx/java/htmlpages/MRI_22.0.3.gif
/usr/local/dx/java/htmlpages/MRI_22.0.4.gif
/usr/local/dx/java/htmlpages/MRI_22.0.5.gif
/usr/local/dx/java/htmlpages/MRI_22.0.6.gif
/usr/local/dx/java/htmlpages/MRI_22.0.7.gif
/usr/local/dx/java/htmlpages/MRI_22.0.8.gif
/usr/local/dx/java/htmlpages/Makefile.am
/usr/local/dx/java/htmlpages/Makefile.in
/usr/local/dx/java/htmlpages/Makefile.sample
/usr/local/dx/java/htmlpages/MutualFund.html
/usr/local/dx/java/htmlpages/MutualFund10.0.0.gif
/usr/local/dx/java/htmlpages/MutualFund2.0.0.gif
/usr/local/dx/java/htmlpages/MutualFund3.0.0.gif
/usr/local/dx/java/htmlpages/Navigation.html
/usr/local/dx/java/htmlpages/Navigation1.0.0.gif
/usr/local/dx/java/htmlpages/Navigation6.0.0.gif
/usr/local/dx/java/htmlpages/Navigation7.0.0.gif
/usr/local/dx/java/htmlpages/ScatterData.html
/usr/local/dx/java/htmlpages/ScatterData3.0.0.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.0.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.1.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.2.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.3.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.4.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.5.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.6.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.7.gif
/usr/local/dx/java/htmlpages/ScatterData4.0.8.gif
/usr/local/dx/java/htmlpages/Status.htm
/usr/local/dx/java/htmlpages/Status.html
/usr/local/dx/java/htmlpages/Streamline.html
/usr/local/dx/java/htmlpages/Streamline2.0.0.gif
/usr/local/dx/java/htmlpages/Streamline3.0.0.gif
/usr/local/dx/java/htmlpages/Streamline3.0.1.gif
/usr/local/dx/java/htmlpages/Streamline3.0.2.gif
/usr/local/dx/java/htmlpages/Streamline3.0.3.gif
/usr/local/dx/java/htmlpages/Streamline3.0.4.gif
/usr/local/dx/java/htmlpages/Streamline3.0.5.gif
/usr/local/dx/java/htmlpages/Streamline3.0.6.gif
/usr/local/dx/java/htmlpages/Streamline3.0.7.gif
/usr/local/dx/java/htmlpages/Streamline3.0.8.gif
/usr/local/dx/java/htmlpages/Streamline7.0.0.gif
/usr/local/dx/java/htmlpages/ThunderGlyphSheet.htm
/usr/local/dx/java/htmlpages/ThunderGlyphSheet.html
/usr/local/dx/java/htmlpages/ThunderGlyphSheet2.0.0.wrl
/usr/local/dx/java/htmlpages/ThunderGlyphSheet3.0.0.gif
/usr/local/dx/java/htmlpages/Topo.gif
/usr/local/dx/java/htmlpages/Topo.html
/usr/local/dx/java/htmlpages/Topo2.0.0.gif
/usr/local/dx/java/htmlpages/Topo3.0.0.gif
/usr/local/dx/java/htmlpages/Topo3.0.1.gif
/usr/local/dx/java/htmlpages/Topo3.0.2.gif
/usr/local/dx/java/htmlpages/Topo3.0.3.gif
/usr/local/dx/java/htmlpages/Topo3.0.4.gif
/usr/local/dx/java/htmlpages/Topo3.0.5.gif
/usr/local/dx/java/htmlpages/Topo3.0.6.gif
/usr/local/dx/java/htmlpages/Topo3.0.7.gif
/usr/local/dx/java/htmlpages/Topo3.0.8.gif
/usr/local/dx/java/htmlpages/Topo4.0.0.gif
/usr/local/dx/java/htmlpages/activex.htm
/usr/local/dx/java/htmlpages/ddi.html
/usr/local/dx/java/htmlpages/ddi5.0.0.gif
/usr/local/dx/java/htmlpages/ddi7.0.0.gif
/usr/local/dx/java/htmlpages/ddi8.0.0.gif
/usr/local/dx/java/htmlpages/earlier.htm
/usr/local/dx/java/htmlpages/gordon.html
/usr/local/dx/java/htmlpages/gordon1.0.0.gif
/usr/local/dx/java/htmlpages/gordon2.0.0.gif
/usr/local/dx/java/htmlpages/hedge.html
/usr/local/dx/java/htmlpages/hedge3.0.0.gif
/usr/local/dx/java/htmlpages/ibmqw.html
/usr/local/dx/java/htmlpages/ibmqw1.0.0.gif
/usr/local/dx/java/htmlpages/ibmqw2.0.0.gif
/usr/local/dx/java/htmlpages/npvcall.html
/usr/local/dx/java/htmlpages/npvcall3.0.0.gif
/usr/local/dx/java/htmlpages/optval.html
/usr/local/dx/java/htmlpages/optval1.0.0.gif
/usr/local/dx/java/htmlpages/pagea.gif
/usr/local/dx/java/htmlpages/pagea2.gif
/usr/local/dx/java/htmlpages/pagea3.gif
/usr/local/dx/java/htmlpages/perp1.0.0.gif
/usr/local/dx/java/htmlpages/perp1.0.1.gif
/usr/local/dx/java/htmlpages/perp1.0.2.gif
/usr/local/dx/java/htmlpages/perp1.0.3.gif
/usr/local/dx/java/htmlpages/perp1.0.4.gif
/usr/local/dx/java/htmlpages/perp1.0.5.gif
/usr/local/dx/java/htmlpages/perp1.0.6.gif
/usr/local/dx/java/htmlpages/perp1.0.7.gif
/usr/local/dx/java/htmlpages/perp1.0.8.gif
/usr/local/dx/java/htmlpages/toc.htm
/usr/local/dx/java/htmlpages/wacc.html
/usr/local/dx/java/htmlpages/wacc1.0.0.gif
