/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_DXServer */

#ifndef _Included_server_DXServer
#define _Included_server_DXServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     server_DXServer
 * Method:    DXLSend
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_server_DXServer_DXLSend
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     server_DXServer
 * Method:    DXLStartDX
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_server_DXServer_DXLStartDX
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     server_DXServer
 * Method:    DXLExitDX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_server_DXServer_DXLExitDX
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
