#ifndef __DXCONFIG_H__
#define __DXCONFIG_H__

@TOP@

#define DXD_VERSION_STRING      "01.01.0001"
#define DXD_COPYRIGHT_STRING	"none"
#define DXD_VERSION 		1
#define DXD_RELEASE 		1
#define DXD_MODIFICATION 	1
#define DXD_ARCHNAME 		"none"
#define PACKAGE 		"none"
#define VERSION 		"none"
#define HAS_M_PI		0
#define HAS_M_SQRT2		0
#define HAS_S_ISDIR		0
#define HAS_sysmp		0
#undef  REQUIRES_GETHOSTNAME_DECLARATION
#undef  REQUIRES_BZERO_DECLARATION

#undef ibm6000

#undef OLD_LESSTIF

#undef USING_BISON
#undef STATFUNC
#undef STATSTRUCT
#undef HAVE_HCLXMINIT
#undef HAVE_HCLXTINIT
#undef HAVE_SYS_ERRLIST
#undef HAVE_SYSCONFIG_NCPUS
#undef ALTERNATE_CXX_SIGNAL

#undef WITH_BUILDLIBS
#undef HAVE_LIBZ
#undef HAVE_LIBCDF
#undef HAVE_LIBJPEG
#undef HAVE_LIBMAGICK
#undef HAVE_LIBDF
#undef HAVE_LIBNETCDF
#undef HAVE_LIBBZLIB
#undef HAVE_LIBDPS
#undef HAVE_LIBFPX
#undef HAVE_LIBJBIG
#undef HAVE_LIBPNG
#undef HAVE_LIBSFIO
#undef HAVE_LIBTIFF
#undef HAVE_LIBTTF
#undef HAVE_TT_FONT_PATH

#undef uint
#undef byte
#undef float32
#undef float64
#undef int16
#undef int32
#undef int8
#undef short
#undef ubyte
#undef uint16
#undef uint32
#undef uint8
#undef ulong
#undef ushort
#undef __int64

#undef uint
#undef SELECT_ARG_TYPE
#undef SOCK_LENGTH_TYPE
#undef GETENV_ARG
#undef HAVE_CC_LIBC_H
#undef HAVE_CC_OSFCN_H
#undef HAVE_DPS_XDPSLIB_H 
#undef HAVE_DPS_DPSXCLIENT_H
#undef HAVE_DPS_PSOPS_H
#undef HAVE_GL_GL_H
#undef HAVE_GL_GLX_H
#undef HAVE_MRM_MRMPUBLI_H
#undef HAVE_X11_COMPOSITE_H
#undef HAVE_X11_COMPOSITEP_H
#undef HAVE_X11_CONSTRAINT_H
#undef HAVE_X11_COREP_H

#undef caddr_t
#undef HAVE_X11_INTRINSIC_H
#undef HAVE_X11_INTRINSICI_H
#undef HAVE_X11_INTRINSICP_H
#undef HAVE_X11_PROTOCOLS_H
#undef HAVE_X11_SHELL_H
#undef HAVE_X11_STRINGDEFS_H
#undef HAVE_X11_X_H
#undef HAVE_X11_XHPLIB_H
#undef HAVE_X11_XATOM_H
#undef HAVE_X11_XLIB_H
#undef HAVE_X11_XLIBXTRA_H
#undef HAVE_X11_XMU_EDITRES_H

#undef ushort
#undef HAVE_X11_XOS_H
#undef HAVE_X11_XUTIL_H
#undef HAVE_X11_CURSORFONT_H
#undef HAVE_X11_KEYSYM_H
#undef HAVE_X11_KEYSYMDEF_H
#undef HAVE_XM_ARROWB_H
#undef HAVE_XM_ARROWBG_H
#undef HAVE_XM_ATOMMGR_H
#undef HAVE_XM_BULLETINB_H
#undef HAVE_XM_BULLETINBP_H
#undef HAVE_XM_CASCADEB_H
#undef HAVE_XM_CASCADEBG_H

#undef uint32
#undef HAVE_XM_COMMAND_H
#undef HAVE_XM_CUTPASTE_H
#undef HAVE_XM_DIALOGS_H
#undef HAVE_XM_DRAGC_H
#undef HAVE_XM_DRAGDROP_H
#undef HAVE_XM_DRAWINGA_H
#undef HAVE_XM_DRAWINGAP_H
#undef HAVE_XM_DRAWNB_H
#undef HAVE_XM_FILESB_H
#undef HAVE_XM_FORM_H
#undef HAVE_XM_FORMP_H
#undef HAVE_XM_FRAME_H

#undef float32
#undef HAVE_XM_FRAMEP_H
#undef HAVE_XM_GADGETP_H
#undef HAVE_XM_LABEL_H
#undef HAVE_XM_LABELG_H
#undef HAVE_XM_LABELGP_H
#undef HAVE_XM_LABELP_H
#undef HAVE_XM_LIST_H
#undef HAVE_XM_MAINW_H
#undef HAVE_XM_MANAGERP_H
#undef HAVE_XM_MENUSHELL_H
#undef HAVE_XM_MESSAGEB_H
#undef HAVE_XM_MWMUTIL_H

#undef ulong
#undef HAVE_XM_PANEDW_H
#undef HAVE_XM_PRIMITIVEP_H
#undef HAVE_XM_PROTOCOLS_H
#undef HAVE_XM_PUSHB_H
#undef HAVE_XM_PUSHBG_H
#undef HAVE_XM_PUSHBP_H
#undef HAVE_XM_REPTYPE_H
#undef HAVE_XM_ROWCOLUMN_H
#undef HAVE_XM_SCALE_H
#undef HAVE_XM_SCROLLBAR_H
#undef HAVE_XM_SCROLLEDW_H
#undef HAVE_XM_SCROLLEDWP_H
#undef HAVE_XM_SELECTIOB_H
#undef HAVE_XM_SEPARATOG_H

#undef uint64
#undef HAVE_XM_SEPARATOGP_H
#undef HAVE_XM_SEPARATOR_H
#undef HAVE_XM_TEXT_H
#undef HAVE_XM_TEXTF_H
#undef HAVE_XM_TOGGLEB_H
#undef HAVE_XM_TOGGLEBG_H
#undef HAVE_XM_XM_H
#undef HAVE_XM_XMP_H
#undef HAVE_XM_XMSTRDEFS_H
#undef HAVE_ALLOCA_H
#undef HAVE_ARPA_INET_H
#undef HAVE_BSTRING_H

#undef uint8
#undef HAVE_CDF_H
#undef HAVE_CONIO_H
#undef HAVE_CRYPT_H
#undef HAVE_CTYPE_H
#undef HAVE_CYGWIN_SOCKET_H
#undef HAVE_DFSD_H
#undef HAVE_DIRECT_H
#undef HAVE_DIRENT_H
#undef HAVE_DL_H
#undef HAVE_DLFCN_H
#undef HAVE_ERRNO_H
#undef HAVE_FCNTL_H

#undef int64
#undef HAVE_FLOAT_H
#undef HAVE_FSTREAM_H
#undef HAVE_GET_H
#undef HAVE_GL_H
#undef HAVE_GL_DEVICE_H
#undef HAVE_GL_GL_H
#undef HAVE_INVENT_H
#undef HAVE_IO_H
#undef HAVE_IOP_AFB_H
#undef HAVE_IOP_MOV_H
#undef HAVE_IOP_PFS_H
#undef HAVE_IOSTREAM_H

#undef int32
#undef HAVE_LICENSE_H
#undef HAVE_LIMITS_H
#undef HAVE_MALLOC_H
#undef HAVE_MATH_H
#undef HAVE_MEMORY_H
#undef HAVE_MINGW32_DIR_H
#undef HAVE_MON_H
#undef HAVE_NET_IF_H
#undef HAVE_NET_IF_ARP_H
#undef HAVE_NET_ROUTE_H
#undef HAVE_NETCDF_H
#undef HAVE_NETDB_H

#undef int16
#undef HAVE_NETINET_IN_H
#undef HAVE_OS2_H
#undef HAVE_PROCESS_H
#undef HAVE_PWD_H
#undef HAVE_REGEXP_H
#undef HAVE_SETJMP_H
#undef HAVE_SIGNAL_H
#undef HAVE_STARBASE_C_H
#undef HAVE_STDARG_H
#undef HAVE_STDDEF_H
#undef HAVE_STDIO_H
#undef HAVE_STDLIB_H

#undef float64
#undef HAVE_STREAM_H
#undef HAVE_STRING_H
#undef HAVE_STRINGS_H
#undef HAVE_STRSTREA_H
#undef HAVE_STRSTREAM_H
#undef HAVE_SYNCH_H
#undef HAVE_SYS_ACCESS_H
#undef HAVE_SYS_BSD_TYPES_H
#undef HAVE_SYS_FILE_H
#undef HAVE_SYS_FILIO_H
#undef HAVE_SYS_IOCTL_H
#undef HAVE_SYS_IPC_H

#undef byte
#undef HAVE_SYS_LDR_H
#undef HAVE_SYS_M88KBCS_H
#undef HAVE_SYS_M_WAIT_H
#undef HAVE_SYS_MMAN_H
#undef HAVE_SYS_MODE_H
#undef HAVE_SYS_PARAM_H
#undef HAVE_SYS_PSTAT_H
#undef HAVE_SYS_RESOURCE_H
#undef HAVE_SYS_SELECT_H
#undef HAVE_SYS_SHM_H
#undef HAVE_SYS_SIGNAL_H
#undef HAVE_SYS_SOCKET_H

#undef uint16
#undef HAVE_SYS_STAT_H
#undef HAVE_SYS_SVS_H
#undef HAVE_SYS_SYSLIMITS_H
#undef HAVE_SYS_SYSMACROS_H
#undef HAVE_SYS_SYSMP_H
#undef HAVE_SYS_SYSCONFIG_H
#undef HAVE_SYS_SYSTEMCFG_H
#undef HAVE_SYS_SYSTEMINFO_H
#undef HAVE_SYS_TIME_H
#undef HAVE_SYS_TIMEB_H
#undef HAVE_SYS_TIMES_H
#undef HAVE_SYS_TYPES_H

#undef ubyte
#undef HAVE_SYS_UN_H
#undef HAVE_SYS_UTSNAME_H
#undef HAVE_SYS_WAIT_H
#undef HAVE_SYSENT_H
#undef HAVE_TIME_H
#undef HAVE_TYPES_H
#undef HAVE_ULOCKS_H
#undef HAVE_UNISTD_H
#undef HAVE_VALUES_H
#undef HAVE_WAIT_H
#undef HAVE_WINBASE_H
#undef HAVE_WINDOWS_H

#undef short
#undef HAVE_WINGDI_H
#undef HAVE_WINIOCTL_H
#undef HAVE_WINSOCK_H
#undef HAVE_X11_XLIBXTRA_H
#undef HAVE_XGL_XGL_H

#undef int8
#undef DXEXEC_EXP
#undef DXEXEC_IMP

#undef HAVE_SIGBUS
#undef HAVE_SIGPIPE
#undef HAVE_SIGKILL
#undef HAVE_SIGDANGER
#undef DX_XLIBS_LIST

#undef HAVE_UNLINK
#undef HAVE__UNLINK
#undef HAVE_GETPID
#undef HAVE__GETPID
#undef HAVE_GETLOGIN

@BOTTOM@

#endif
