"macro dxexport(",
" object",
",base_name",
") -> (",
" file_written",
") {",
"dxexport_Input_7_o1 = object;",
"dxexport_Input_8_o1 = base_name;",
"Export(",
"dxexport_Input_7_o1,",
"dxexport_Input_8_o1,",
"\"dx text follows\"",
") [instance: 1, cache: 1];",
"dxexport_Format_8_o1[cache: 2] = ",
"Format(",
"\"%s.dx\",",
"dxexport_Input_8_o1,",
"NULL",
") [instance: 8, cache: 1];",
"file_written = dxexport_Format_8_o1;",
"}",
